// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/miners/v1/query.proto

package typespb

import (
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryMinerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMinerRequest) Reset() {
	*x = QueryMinerRequest{}
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMinerRequest) ProtoMessage() {}

func (x *QueryMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMinerRequest.ProtoReflect.Descriptor instead.
func (*QueryMinerRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMinerRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type QueryMinerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Miner         *Miner                 `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMinerResponse) Reset() {
	*x = QueryMinerResponse{}
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMinerResponse) ProtoMessage() {}

func (x *QueryMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMinerResponse.ProtoReflect.Descriptor instead.
func (*QueryMinerResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryMinerResponse) GetMiner() *Miner {
	if x != nil {
		return x.Miner
	}
	return nil
}

type QueryMinersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMinersRequest) Reset() {
	*x = QueryMinersRequest{}
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMinersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMinersRequest) ProtoMessage() {}

func (x *QueryMinersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMinersRequest.ProtoReflect.Descriptor instead.
func (*QueryMinersRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryMinersRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryMinersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Miners        []*Miner               `protobuf:"bytes,1,rep,name=miners,proto3" json:"miners,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMinersResponse) Reset() {
	*x = QueryMinersResponse{}
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMinersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMinersResponse) ProtoMessage() {}

func (x *QueryMinersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMinersResponse.ProtoReflect.Descriptor instead.
func (*QueryMinersResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryMinersResponse) GetMiners() []*Miner {
	if x != nil {
		return x.Miners
	}
	return nil
}

func (x *QueryMinersResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_query_proto_rawDescGZIP(), []int{4}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_contentgrid_miners_v1_query_proto protoreflect.FileDescriptor

const file_contentgrid_miners_v1_query_proto_rawDesc = "" +
	"\n" +
	"!contentgrid/miners/v1/query.proto\x12\x15contentgrid.miners.v1\x1a!contentgrid/miners/v1/types.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"/\n" +
	"\x11QueryMinerRequest\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\"H\n" +
	"\x12QueryMinerResponse\x122\n" +
	"\x05miner\x18\x01 \x01(\v2\x1c.contentgrid.miners.v1.MinerR\x05miner\"\\\n" +
	"\x12QueryMinersRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x94\x01\n" +
	"\x13QueryMinersResponse\x124\n" +
	"\x06miners\x18\x01 \x03(\v2\x1c.contentgrid.miners.v1.MinerR\x06miners\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"\x14\n" +
	"\x12QueryParamsRequest\"L\n" +
	"\x13QueryParamsResponse\x125\n" +
	"\x06params\x18\x01 \x01(\v2\x1d.contentgrid.miners.v1.ParamsR\x06params2\xad\x03\n" +
	"\x05Query\x12\x8f\x01\n" +
	"\x05Miner\x12(.contentgrid.miners.v1.QueryMinerRequest\x1a).contentgrid.miners.v1.QueryMinerResponse\"1\x82\xd3\xe4\x93\x02+\x12)/content-grid/miners/v1/miners/{operator}\x12\x87\x01\n" +
	"\x06Miners\x12).contentgrid.miners.v1.QueryMinersRequest\x1a*.contentgrid.miners.v1.QueryMinersResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/content-grid/miners/v1/miners\x12\x87\x01\n" +
	"\x06Params\x12).contentgrid.miners.v1.QueryParamsRequest\x1a*.contentgrid.miners.v1.QueryParamsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/content-grid/miners/v1/paramsB%Z#content-grid-chain/x/miners/typespbb\x06proto3"

var (
	file_contentgrid_miners_v1_query_proto_rawDescOnce sync.Once
	file_contentgrid_miners_v1_query_proto_rawDescData []byte
)

func file_contentgrid_miners_v1_query_proto_rawDescGZIP() []byte {
	file_contentgrid_miners_v1_query_proto_rawDescOnce.Do(func() {
		file_contentgrid_miners_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_miners_v1_query_proto_rawDesc), len(file_contentgrid_miners_v1_query_proto_rawDesc)))
	})
	return file_contentgrid_miners_v1_query_proto_rawDescData
}

var file_contentgrid_miners_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contentgrid_miners_v1_query_proto_goTypes = []any{
	(*QueryMinerRequest)(nil),   // 0: contentgrid.miners.v1.QueryMinerRequest
	(*QueryMinerResponse)(nil),  // 1: contentgrid.miners.v1.QueryMinerResponse
	(*QueryMinersRequest)(nil),  // 2: contentgrid.miners.v1.QueryMinersRequest
	(*QueryMinersResponse)(nil), // 3: contentgrid.miners.v1.QueryMinersResponse
	(*QueryParamsRequest)(nil),  // 4: contentgrid.miners.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil), // 5: contentgrid.miners.v1.QueryParamsResponse
	(*Miner)(nil),               // 6: contentgrid.miners.v1.Miner
	(*query.PageRequest)(nil),   // 7: cosmos.base.query.v1beta1.PageRequest
	(*query.PageResponse)(nil),  // 8: cosmos.base.query.v1beta1.PageResponse
	(*Params)(nil),              // 9: contentgrid.miners.v1.Params
}
var file_contentgrid_miners_v1_query_proto_depIdxs = []int32{
	6, // 0: contentgrid.miners.v1.QueryMinerResponse.miner:type_name -> contentgrid.miners.v1.Miner
	7, // 1: contentgrid.miners.v1.QueryMinersRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	6, // 2: contentgrid.miners.v1.QueryMinersResponse.miners:type_name -> contentgrid.miners.v1.Miner
	8, // 3: contentgrid.miners.v1.QueryMinersResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	9, // 4: contentgrid.miners.v1.QueryParamsResponse.params:type_name -> contentgrid.miners.v1.Params
	0, // 5: contentgrid.miners.v1.Query.Miner:input_type -> contentgrid.miners.v1.QueryMinerRequest
	2, // 6: contentgrid.miners.v1.Query.Miners:input_type -> contentgrid.miners.v1.QueryMinersRequest
	4, // 7: contentgrid.miners.v1.Query.Params:input_type -> contentgrid.miners.v1.QueryParamsRequest
	1, // 8: contentgrid.miners.v1.Query.Miner:output_type -> contentgrid.miners.v1.QueryMinerResponse
	3, // 9: contentgrid.miners.v1.Query.Miners:output_type -> contentgrid.miners.v1.QueryMinersResponse
	5, // 10: contentgrid.miners.v1.Query.Params:output_type -> contentgrid.miners.v1.QueryParamsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_contentgrid_miners_v1_query_proto_init() }
func file_contentgrid_miners_v1_query_proto_init() {
	if File_contentgrid_miners_v1_query_proto != nil {
		return
	}
	file_contentgrid_miners_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_miners_v1_query_proto_rawDesc), len(file_contentgrid_miners_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contentgrid_miners_v1_query_proto_goTypes,
		DependencyIndexes: file_contentgrid_miners_v1_query_proto_depIdxs,
		MessageInfos:      file_contentgrid_miners_v1_query_proto_msgTypes,
	}.Build()
	File_contentgrid_miners_v1_query_proto = out.File
	file_contentgrid_miners_v1_query_proto_goTypes = nil
	file_contentgrid_miners_v1_query_proto_depIdxs = nil
}
