// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/miners/v1/tx.proto

package typespb

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgRegisterMiner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	MetadataUri   string                 `protobuf:"bytes,2,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	Services      uint32                 `protobuf:"varint,3,opt,name=services,proto3" json:"services,omitempty"`
	MinBidDenom   string                 `protobuf:"bytes,4,opt,name=min_bid_denom,json=minBidDenom,proto3" json:"min_bid_denom,omitempty"`
	MinBidAmount  string                 `protobuf:"bytes,5,opt,name=min_bid_amount,json=minBidAmount,proto3" json:"min_bid_amount,omitempty"`
	Stake         string                 `protobuf:"bytes,6,opt,name=stake,proto3" json:"stake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterMiner) Reset() {
	*x = MsgRegisterMiner{}
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterMiner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterMiner) ProtoMessage() {}

func (x *MsgRegisterMiner) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterMiner.ProtoReflect.Descriptor instead.
func (*MsgRegisterMiner) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgRegisterMiner) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *MsgRegisterMiner) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *MsgRegisterMiner) GetServices() uint32 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *MsgRegisterMiner) GetMinBidDenom() string {
	if x != nil {
		return x.MinBidDenom
	}
	return ""
}

func (x *MsgRegisterMiner) GetMinBidAmount() string {
	if x != nil {
		return x.MinBidAmount
	}
	return ""
}

func (x *MsgRegisterMiner) GetStake() string {
	if x != nil {
		return x.Stake
	}
	return ""
}

type MsgRegisterMinerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Miner         *Miner                 `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterMinerResponse) Reset() {
	*x = MsgRegisterMinerResponse{}
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterMinerResponse) ProtoMessage() {}

func (x *MsgRegisterMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterMinerResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterMinerResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgRegisterMinerResponse) GetMiner() *Miner {
	if x != nil {
		return x.Miner
	}
	return nil
}

type MsgUpdateMiner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	MetadataUri   string                 `protobuf:"bytes,2,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	Services      uint32                 `protobuf:"varint,3,opt,name=services,proto3" json:"services,omitempty"`
	MinBidDenom   string                 `protobuf:"bytes,4,opt,name=min_bid_denom,json=minBidDenom,proto3" json:"min_bid_denom,omitempty"`
	MinBidAmount  string                 `protobuf:"bytes,5,opt,name=min_bid_amount,json=minBidAmount,proto3" json:"min_bid_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateMiner) Reset() {
	*x = MsgUpdateMiner{}
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateMiner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateMiner) ProtoMessage() {}

func (x *MsgUpdateMiner) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateMiner.ProtoReflect.Descriptor instead.
func (*MsgUpdateMiner) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgUpdateMiner) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *MsgUpdateMiner) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *MsgUpdateMiner) GetServices() uint32 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *MsgUpdateMiner) GetMinBidDenom() string {
	if x != nil {
		return x.MinBidDenom
	}
	return ""
}

func (x *MsgUpdateMiner) GetMinBidAmount() string {
	if x != nil {
		return x.MinBidAmount
	}
	return ""
}

type MsgUpdateMinerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Miner         *Miner                 `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateMinerResponse) Reset() {
	*x = MsgUpdateMinerResponse{}
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateMinerResponse) ProtoMessage() {}

func (x *MsgUpdateMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateMinerResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateMinerResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgUpdateMinerResponse) GetMiner() *Miner {
	if x != nil {
		return x.Miner
	}
	return nil
}

type MsgUpdateMinerStake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	StakeDelta    string                 `protobuf:"bytes,2,opt,name=stake_delta,json=stakeDelta,proto3" json:"stake_delta,omitempty"`
	Increase      bool                   `protobuf:"varint,3,opt,name=increase,proto3" json:"increase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateMinerStake) Reset() {
	*x = MsgUpdateMinerStake{}
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateMinerStake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateMinerStake) ProtoMessage() {}

func (x *MsgUpdateMinerStake) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateMinerStake.ProtoReflect.Descriptor instead.
func (*MsgUpdateMinerStake) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgUpdateMinerStake) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *MsgUpdateMinerStake) GetStakeDelta() string {
	if x != nil {
		return x.StakeDelta
	}
	return ""
}

func (x *MsgUpdateMinerStake) GetIncrease() bool {
	if x != nil {
		return x.Increase
	}
	return false
}

type MsgUpdateMinerStakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Miner         *Miner                 `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateMinerStakeResponse) Reset() {
	*x = MsgUpdateMinerStakeResponse{}
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateMinerStakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateMinerStakeResponse) ProtoMessage() {}

func (x *MsgUpdateMinerStakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateMinerStakeResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateMinerStakeResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgUpdateMinerStakeResponse) GetMiner() *Miner {
	if x != nil {
		return x.Miner
	}
	return nil
}

var File_contentgrid_miners_v1_tx_proto protoreflect.FileDescriptor

const file_contentgrid_miners_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1econtentgrid/miners/v1/tx.proto\x12\x15contentgrid.miners.v1\x1a!contentgrid/miners/v1/types.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\"\xdc\x01\n" +
	"\x10MsgRegisterMiner\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12!\n" +
	"\fmetadata_uri\x18\x02 \x01(\tR\vmetadataUri\x12\x1a\n" +
	"\bservices\x18\x03 \x01(\rR\bservices\x12\"\n" +
	"\rmin_bid_denom\x18\x04 \x01(\tR\vminBidDenom\x12$\n" +
	"\x0emin_bid_amount\x18\x05 \x01(\tR\fminBidAmount\x12\x14\n" +
	"\x05stake\x18\x06 \x01(\tR\x05stake:\r\x82\xe7\xb0*\boperator\"N\n" +
	"\x18MsgRegisterMinerResponse\x122\n" +
	"\x05miner\x18\x01 \x01(\v2\x1c.contentgrid.miners.v1.MinerR\x05miner\"\xc4\x01\n" +
	"\x0eMsgUpdateMiner\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12!\n" +
	"\fmetadata_uri\x18\x02 \x01(\tR\vmetadataUri\x12\x1a\n" +
	"\bservices\x18\x03 \x01(\rR\bservices\x12\"\n" +
	"\rmin_bid_denom\x18\x04 \x01(\tR\vminBidDenom\x12$\n" +
	"\x0emin_bid_amount\x18\x05 \x01(\tR\fminBidAmount:\r\x82\xe7\xb0*\boperator\"L\n" +
	"\x16MsgUpdateMinerResponse\x122\n" +
	"\x05miner\x18\x01 \x01(\v2\x1c.contentgrid.miners.v1.MinerR\x05miner\"}\n" +
	"\x13MsgUpdateMinerStake\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12\x1f\n" +
	"\vstake_delta\x18\x02 \x01(\tR\n" +
	"stakeDelta\x12\x1a\n" +
	"\bincrease\x18\x03 \x01(\bR\bincrease:\r\x82\xe7\xb0*\boperator\"Q\n" +
	"\x1bMsgUpdateMinerStakeResponse\x122\n" +
	"\x05miner\x18\x01 \x01(\v2\x1c.contentgrid.miners.v1.MinerR\x05miner2\xd0\x02\n" +
	"\x03Msg\x12i\n" +
	"\rRegisterMiner\x12'.contentgrid.miners.v1.MsgRegisterMiner\x1a/.contentgrid.miners.v1.MsgRegisterMinerResponse\x12c\n" +
	"\vUpdateMiner\x12%.contentgrid.miners.v1.MsgUpdateMiner\x1a-.contentgrid.miners.v1.MsgUpdateMinerResponse\x12r\n" +
	"\x10UpdateMinerStake\x12*.contentgrid.miners.v1.MsgUpdateMinerStake\x1a2.contentgrid.miners.v1.MsgUpdateMinerStakeResponse\x1a\x05\x80\xe7\xb0*\x01B%Z#content-grid-chain/x/miners/typespbb\x06proto3"

var (
	file_contentgrid_miners_v1_tx_proto_rawDescOnce sync.Once
	file_contentgrid_miners_v1_tx_proto_rawDescData []byte
)

func file_contentgrid_miners_v1_tx_proto_rawDescGZIP() []byte {
	file_contentgrid_miners_v1_tx_proto_rawDescOnce.Do(func() {
		file_contentgrid_miners_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_miners_v1_tx_proto_rawDesc), len(file_contentgrid_miners_v1_tx_proto_rawDesc)))
	})
	return file_contentgrid_miners_v1_tx_proto_rawDescData
}

var file_contentgrid_miners_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contentgrid_miners_v1_tx_proto_goTypes = []any{
	(*MsgRegisterMiner)(nil),            // 0: contentgrid.miners.v1.MsgRegisterMiner
	(*MsgRegisterMinerResponse)(nil),    // 1: contentgrid.miners.v1.MsgRegisterMinerResponse
	(*MsgUpdateMiner)(nil),              // 2: contentgrid.miners.v1.MsgUpdateMiner
	(*MsgUpdateMinerResponse)(nil),      // 3: contentgrid.miners.v1.MsgUpdateMinerResponse
	(*MsgUpdateMinerStake)(nil),         // 4: contentgrid.miners.v1.MsgUpdateMinerStake
	(*MsgUpdateMinerStakeResponse)(nil), // 5: contentgrid.miners.v1.MsgUpdateMinerStakeResponse
	(*Miner)(nil),                       // 6: contentgrid.miners.v1.Miner
}
var file_contentgrid_miners_v1_tx_proto_depIdxs = []int32{
	6, // 0: contentgrid.miners.v1.MsgRegisterMinerResponse.miner:type_name -> contentgrid.miners.v1.Miner
	6, // 1: contentgrid.miners.v1.MsgUpdateMinerResponse.miner:type_name -> contentgrid.miners.v1.Miner
	6, // 2: contentgrid.miners.v1.MsgUpdateMinerStakeResponse.miner:type_name -> contentgrid.miners.v1.Miner
	0, // 3: contentgrid.miners.v1.Msg.RegisterMiner:input_type -> contentgrid.miners.v1.MsgRegisterMiner
	2, // 4: contentgrid.miners.v1.Msg.UpdateMiner:input_type -> contentgrid.miners.v1.MsgUpdateMiner
	4, // 5: contentgrid.miners.v1.Msg.UpdateMinerStake:input_type -> contentgrid.miners.v1.MsgUpdateMinerStake
	1, // 6: contentgrid.miners.v1.Msg.RegisterMiner:output_type -> contentgrid.miners.v1.MsgRegisterMinerResponse
	3, // 7: contentgrid.miners.v1.Msg.UpdateMiner:output_type -> contentgrid.miners.v1.MsgUpdateMinerResponse
	5, // 8: contentgrid.miners.v1.Msg.UpdateMinerStake:output_type -> contentgrid.miners.v1.MsgUpdateMinerStakeResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contentgrid_miners_v1_tx_proto_init() }
func file_contentgrid_miners_v1_tx_proto_init() {
	if File_contentgrid_miners_v1_tx_proto != nil {
		return
	}
	file_contentgrid_miners_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_miners_v1_tx_proto_rawDesc), len(file_contentgrid_miners_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contentgrid_miners_v1_tx_proto_goTypes,
		DependencyIndexes: file_contentgrid_miners_v1_tx_proto_depIdxs,
		MessageInfos:      file_contentgrid_miners_v1_tx_proto_msgTypes,
	}.Build()
	File_contentgrid_miners_v1_tx_proto = out.File
	file_contentgrid_miners_v1_tx_proto_goTypes = nil
	file_contentgrid_miners_v1_tx_proto_depIdxs = nil
}
