// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: contentgrid/miners/v1/tx.proto

package typespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_RegisterMiner_FullMethodName    = "/contentgrid.miners.v1.Msg/RegisterMiner"
	Msg_UpdateMiner_FullMethodName      = "/contentgrid.miners.v1.Msg/UpdateMiner"
	Msg_UpdateMinerStake_FullMethodName = "/contentgrid.miners.v1.Msg/UpdateMinerStake"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	RegisterMiner(ctx context.Context, in *MsgRegisterMiner, opts ...grpc.CallOption) (*MsgRegisterMinerResponse, error)
	UpdateMiner(ctx context.Context, in *MsgUpdateMiner, opts ...grpc.CallOption) (*MsgUpdateMinerResponse, error)
	UpdateMinerStake(ctx context.Context, in *MsgUpdateMinerStake, opts ...grpc.CallOption) (*MsgUpdateMinerStakeResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterMiner(ctx context.Context, in *MsgRegisterMiner, opts ...grpc.CallOption) (*MsgRegisterMinerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterMinerResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterMiner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateMiner(ctx context.Context, in *MsgUpdateMiner, opts ...grpc.CallOption) (*MsgUpdateMinerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateMinerResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateMiner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateMinerStake(ctx context.Context, in *MsgUpdateMinerStake, opts ...grpc.CallOption) (*MsgUpdateMinerStakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateMinerStakeResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateMinerStake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
type MsgServer interface {
	RegisterMiner(context.Context, *MsgRegisterMiner) (*MsgRegisterMinerResponse, error)
	UpdateMiner(context.Context, *MsgUpdateMiner) (*MsgUpdateMinerResponse, error)
	UpdateMinerStake(context.Context, *MsgUpdateMinerStake) (*MsgUpdateMinerStakeResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) RegisterMiner(context.Context, *MsgRegisterMiner) (*MsgRegisterMinerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterMiner not implemented")
}
func (UnimplementedMsgServer) UpdateMiner(context.Context, *MsgUpdateMiner) (*MsgUpdateMinerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMiner not implemented")
}
func (UnimplementedMsgServer) UpdateMinerStake(context.Context, *MsgUpdateMinerStake) (*MsgUpdateMinerStakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMinerStake not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_RegisterMiner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterMiner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterMiner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterMiner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterMiner(ctx, req.(*MsgRegisterMiner))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateMiner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateMiner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateMiner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateMiner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateMiner(ctx, req.(*MsgUpdateMiner))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateMinerStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateMinerStake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateMinerStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateMinerStake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateMinerStake(ctx, req.(*MsgUpdateMinerStake))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contentgrid.miners.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterMiner",
			Handler:    _Msg_RegisterMiner_Handler,
		},
		{
			MethodName: "UpdateMiner",
			Handler:    _Msg_UpdateMiner_Handler,
		},
		{
			MethodName: "UpdateMinerStake",
			Handler:    _Msg_UpdateMinerStake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contentgrid/miners/v1/tx.proto",
}
