// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/miners/v1/types.proto

package typespb

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MinerStatus int32

const (
	MinerStatus_MINER_STATUS_UNSPECIFIED MinerStatus = 0
	MinerStatus_MINER_STATUS_PENDING     MinerStatus = 1
	MinerStatus_MINER_STATUS_ACTIVE      MinerStatus = 2
	MinerStatus_MINER_STATUS_JAILED      MinerStatus = 3
)

// Enum value maps for MinerStatus.
var (
	MinerStatus_name = map[int32]string{
		0: "MINER_STATUS_UNSPECIFIED",
		1: "MINER_STATUS_PENDING",
		2: "MINER_STATUS_ACTIVE",
		3: "MINER_STATUS_JAILED",
	}
	MinerStatus_value = map[string]int32{
		"MINER_STATUS_UNSPECIFIED": 0,
		"MINER_STATUS_PENDING":     1,
		"MINER_STATUS_ACTIVE":      2,
		"MINER_STATUS_JAILED":      3,
	}
)

func (x MinerStatus) Enum() *MinerStatus {
	p := new(MinerStatus)
	*p = x
	return p
}

func (x MinerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contentgrid_miners_v1_types_proto_enumTypes[0].Descriptor()
}

func (MinerStatus) Type() protoreflect.EnumType {
	return &file_contentgrid_miners_v1_types_proto_enumTypes[0]
}

func (x MinerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MinerStatus.Descriptor instead.
func (MinerStatus) EnumDescriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_types_proto_rawDescGZIP(), []int{0}
}

type Miner struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Operator           string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	MetadataUri        string                 `protobuf:"bytes,2,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	Services           uint32                 `protobuf:"varint,3,opt,name=services,proto3" json:"services,omitempty"`
	MinBidDenom        string                 `protobuf:"bytes,4,opt,name=min_bid_denom,json=minBidDenom,proto3" json:"min_bid_denom,omitempty"`
	MinBidAmount       string                 `protobuf:"bytes,5,opt,name=min_bid_amount,json=minBidAmount,proto3" json:"min_bid_amount,omitempty"`
	Stake              string                 `protobuf:"bytes,6,opt,name=stake,proto3" json:"stake,omitempty"`
	Status             MinerStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=contentgrid.miners.v1.MinerStatus" json:"status,omitempty"`
	RegisteredAtHeight int64                  `protobuf:"varint,8,opt,name=registered_at_height,json=registeredAtHeight,proto3" json:"registered_at_height,omitempty"`
	LastUpdateHeight   int64                  `protobuf:"varint,9,opt,name=last_update_height,json=lastUpdateHeight,proto3" json:"last_update_height,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Miner) Reset() {
	*x = Miner{}
	mi := &file_contentgrid_miners_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Miner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Miner) ProtoMessage() {}

func (x *Miner) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Miner.ProtoReflect.Descriptor instead.
func (*Miner) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Miner) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Miner) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *Miner) GetServices() uint32 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *Miner) GetMinBidDenom() string {
	if x != nil {
		return x.MinBidDenom
	}
	return ""
}

func (x *Miner) GetMinBidAmount() string {
	if x != nil {
		return x.MinBidAmount
	}
	return ""
}

func (x *Miner) GetStake() string {
	if x != nil {
		return x.Stake
	}
	return ""
}

func (x *Miner) GetStatus() MinerStatus {
	if x != nil {
		return x.Status
	}
	return MinerStatus_MINER_STATUS_UNSPECIFIED
}

func (x *Miner) GetRegisteredAtHeight() int64 {
	if x != nil {
		return x.RegisteredAtHeight
	}
	return 0
}

func (x *Miner) GetLastUpdateHeight() int64 {
	if x != nil {
		return x.LastUpdateHeight
	}
	return 0
}

type Params struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StakeDenom        string                 `protobuf:"bytes,1,opt,name=stake_denom,json=stakeDenom,proto3" json:"stake_denom,omitempty"`
	MinStake          string                 `protobuf:"bytes,2,opt,name=min_stake,json=minStake,proto3" json:"min_stake,omitempty"`
	MaxMetadataLength uint32                 `protobuf:"varint,3,opt,name=max_metadata_length,json=maxMetadataLength,proto3" json:"max_metadata_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_contentgrid_miners_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_miners_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_contentgrid_miners_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Params) GetStakeDenom() string {
	if x != nil {
		return x.StakeDenom
	}
	return ""
}

func (x *Params) GetMinStake() string {
	if x != nil {
		return x.MinStake
	}
	return ""
}

func (x *Params) GetMaxMetadataLength() uint32 {
	if x != nil {
		return x.MaxMetadataLength
	}
	return 0
}

var File_contentgrid_miners_v1_types_proto protoreflect.FileDescriptor

const file_contentgrid_miners_v1_types_proto_rawDesc = "" +
	"\n" +
	"!contentgrid/miners/v1/types.proto\x12\x15contentgrid.miners.v1\x1a\x14gogoproto/gogo.proto\"\xde\x02\n" +
	"\x05Miner\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12!\n" +
	"\fmetadata_uri\x18\x02 \x01(\tR\vmetadataUri\x12\x1a\n" +
	"\bservices\x18\x03 \x01(\rR\bservices\x12\"\n" +
	"\rmin_bid_denom\x18\x04 \x01(\tR\vminBidDenom\x12$\n" +
	"\x0emin_bid_amount\x18\x05 \x01(\tR\fminBidAmount\x12\x14\n" +
	"\x05stake\x18\x06 \x01(\tR\x05stake\x12:\n" +
	"\x06status\x18\a \x01(\x0e2\".contentgrid.miners.v1.MinerStatusR\x06status\x120\n" +
	"\x14registered_at_height\x18\b \x01(\x03R\x12registeredAtHeight\x12,\n" +
	"\x12last_update_height\x18\t \x01(\x03R\x10lastUpdateHeight\"v\n" +
	"\x06Params\x12\x1f\n" +
	"\vstake_denom\x18\x01 \x01(\tR\n" +
	"stakeDenom\x12\x1b\n" +
	"\tmin_stake\x18\x02 \x01(\tR\bminStake\x12.\n" +
	"\x13max_metadata_length\x18\x03 \x01(\rR\x11maxMetadataLength*w\n" +
	"\vMinerStatus\x12\x1c\n" +
	"\x18MINER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MINER_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13MINER_STATUS_ACTIVE\x10\x02\x12\x17\n" +
	"\x13MINER_STATUS_JAILED\x10\x03B%Z#content-grid-chain/x/miners/typespbb\x06proto3"

var (
	file_contentgrid_miners_v1_types_proto_rawDescOnce sync.Once
	file_contentgrid_miners_v1_types_proto_rawDescData []byte
)

func file_contentgrid_miners_v1_types_proto_rawDescGZIP() []byte {
	file_contentgrid_miners_v1_types_proto_rawDescOnce.Do(func() {
		file_contentgrid_miners_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_miners_v1_types_proto_rawDesc), len(file_contentgrid_miners_v1_types_proto_rawDesc)))
	})
	return file_contentgrid_miners_v1_types_proto_rawDescData
}

var file_contentgrid_miners_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contentgrid_miners_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contentgrid_miners_v1_types_proto_goTypes = []any{
	(MinerStatus)(0), // 0: contentgrid.miners.v1.MinerStatus
	(*Miner)(nil),    // 1: contentgrid.miners.v1.Miner
	(*Params)(nil),   // 2: contentgrid.miners.v1.Params
}
var file_contentgrid_miners_v1_types_proto_depIdxs = []int32{
	0, // 0: contentgrid.miners.v1.Miner.status:type_name -> contentgrid.miners.v1.MinerStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contentgrid_miners_v1_types_proto_init() }
func file_contentgrid_miners_v1_types_proto_init() {
	if File_contentgrid_miners_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_miners_v1_types_proto_rawDesc), len(file_contentgrid_miners_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contentgrid_miners_v1_types_proto_goTypes,
		DependencyIndexes: file_contentgrid_miners_v1_types_proto_depIdxs,
		EnumInfos:         file_contentgrid_miners_v1_types_proto_enumTypes,
		MessageInfos:      file_contentgrid_miners_v1_types_proto_msgTypes,
	}.Build()
	File_contentgrid_miners_v1_types_proto = out.File
	file_contentgrid_miners_v1_types_proto_goTypes = nil
	file_contentgrid_miners_v1_types_proto_depIdxs = nil
}
