package registry

const (
	EventTypePublisherRegistered   = "publisher_registered"
	EventTypeVerificationAssigned  = "publisher_verification_assigned"
	EventTypeVerificationCommitted = "publisher_verification_committed"
	EventTypeVerificationRevealed  = "publisher_verification_revealed"
	EventTypeVerificationSubmitted = "publisher_verification_submitted"
	EventTypeVerificationFinalized = "publisher_verification_finalized"
	EventTypePublisherVerified     = "publisher_verified"
	EventTypeSlotCreated           = "slot_created"
	EventTypeSlotStatusUpdated     = "slot_status_updated"
	EventTypeSlotLeased            = "slot_leased"
	EventTypeLeaseSettled          = "slot_lease_settled"
	EventTypeLeaseViolated         = "slot_lease_violated"
	EventTypePublisherCooldown     = "publisher_cooldown"
	EventTypeVerifierPenalized     = "verifier_penalized"

	AttributeKeyDomain          = "domain"
	AttributeKeyOwner           = "owner"
	AttributeKeyVerifier        = "verifier"
	AttributeKeyReferrer        = "referrer"
	AttributeKeyStatus          = "status"
	AttributeKeyMetadataURI     = "metadata_uri"
	AttributeKeyRoundStart      = "round_start_unix"
	AttributeKeyStartAt         = "start_at_unix"
	AttributeKeyDeadline        = "deadline_unix"
	AttributeKeyObservedAt      = "observed_at_unix"
	AttributeKeyLatencyMs       = "latency_ms"
	AttributeKeyPasses          = "passes"
	AttributeKeyFails           = "fails"
	AttributeKeyQuorum          = "quorum"
	AttributeKeyVerified        = "verified"
	AttributeKeySubmissionCount = "submission_count"
	AttributeKeyVerifierCount   = "verifier_count"
	AttributeKeyObservedSimilar = "observed_similar_domains"
	AttributeKeyMatchedSimilar  = "matched_similar_domains"
	AttributeKeyExpectedSimilar = "expected_similar_domains"
	AttributeKeyExpectedHash    = "expected_set_hash"
	AttributeKeyObservedHash    = "observed_set_hash"
	AttributeKeyCommitHash      = "commit_hash"
	AttributeKeyEvidenceHash    = "evidence_hash"
	AttributeKeySlotID          = "slot_id"
	AttributeKeyLeaseID         = "lease_id"
	AttributeKeySlotStatus      = "slot_status"
	AttributeKeyLeaseStatus     = "lease_status"
	AttributeKeyPayoutAmount    = "payout_amount"
	AttributeKeyCooldownUntil   = "cooldown_until_unix"
	AttributeKeyCooldownCount   = "cooldown_count"
	AttributeKeyPenaltyReason   = "penalty_reason"
	AttributeKeyPenaltyCount    = "penalty_count"
	AttributeKeySuspendedUntil  = "suspended_until_unix"
)
