// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/verifiers/v1/query.proto

package typespb

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryVerifierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVerifierRequest) Reset() {
	*x = QueryVerifierRequest{}
	mi := &file_contentgrid_verifiers_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVerifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVerifierRequest) ProtoMessage() {}

func (x *QueryVerifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVerifierRequest.ProtoReflect.Descriptor instead.
func (*QueryVerifierRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryVerifierRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type QueryVerifierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifier      *Verifier              `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVerifierResponse) Reset() {
	*x = QueryVerifierResponse{}
	mi := &file_contentgrid_verifiers_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVerifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVerifierResponse) ProtoMessage() {}

func (x *QueryVerifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVerifierResponse.ProtoReflect.Descriptor instead.
func (*QueryVerifierResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryVerifierResponse) GetVerifier() *Verifier {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type QueryVerifiersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVerifiersRequest) Reset() {
	*x = QueryVerifiersRequest{}
	mi := &file_contentgrid_verifiers_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVerifiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVerifiersRequest) ProtoMessage() {}

func (x *QueryVerifiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVerifiersRequest.ProtoReflect.Descriptor instead.
func (*QueryVerifiersRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_query_proto_rawDescGZIP(), []int{2}
}

type QueryVerifiersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifiers     []*Verifier            `protobuf:"bytes,1,rep,name=verifiers,proto3" json:"verifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVerifiersResponse) Reset() {
	*x = QueryVerifiersResponse{}
	mi := &file_contentgrid_verifiers_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVerifiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVerifiersResponse) ProtoMessage() {}

func (x *QueryVerifiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVerifiersResponse.ProtoReflect.Descriptor instead.
func (*QueryVerifiersResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryVerifiersResponse) GetVerifiers() []*Verifier {
	if x != nil {
		return x.Verifiers
	}
	return nil
}

var File_contentgrid_verifiers_v1_query_proto protoreflect.FileDescriptor

const file_contentgrid_verifiers_v1_query_proto_rawDesc = "" +
	"\n" +
	"$contentgrid/verifiers/v1/query.proto\x12\x18contentgrid.verifiers.v1\x1a$contentgrid/verifiers/v1/types.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x14QueryVerifierRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"W\n" +
	"\x15QueryVerifierResponse\x12>\n" +
	"\bverifier\x18\x01 \x01(\v2\".contentgrid.verifiers.v1.VerifierR\bverifier\"\x17\n" +
	"\x15QueryVerifiersRequest\"Z\n" +
	"\x16QueryVerifiersResponse\x12@\n" +
	"\tverifiers\x18\x01 \x03(\v2\".contentgrid.verifiers.v1.VerifierR\tverifiers2\xcc\x02\n" +
	"\x05Query\x12\xa3\x01\n" +
	"\bVerifier\x12..contentgrid.verifiers.v1.QueryVerifierRequest\x1a/.contentgrid.verifiers.v1.QueryVerifierResponse\"6\x82\xd3\xe4\x93\x020\x12./content-grid/verifiers/v1/verifiers/{address}\x12\x9c\x01\n" +
	"\tVerifiers\x12/.contentgrid.verifiers.v1.QueryVerifiersRequest\x1a0.contentgrid.verifiers.v1.QueryVerifiersResponse\",\x82\xd3\xe4\x93\x02&\x12$/content-grid/verifiers/v1/verifiersB(Z&content-grid-chain/x/verifiers/typespbb\x06proto3"

var (
	file_contentgrid_verifiers_v1_query_proto_rawDescOnce sync.Once
	file_contentgrid_verifiers_v1_query_proto_rawDescData []byte
)

func file_contentgrid_verifiers_v1_query_proto_rawDescGZIP() []byte {
	file_contentgrid_verifiers_v1_query_proto_rawDescOnce.Do(func() {
		file_contentgrid_verifiers_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_verifiers_v1_query_proto_rawDesc), len(file_contentgrid_verifiers_v1_query_proto_rawDesc)))
	})
	return file_contentgrid_verifiers_v1_query_proto_rawDescData
}

var file_contentgrid_verifiers_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contentgrid_verifiers_v1_query_proto_goTypes = []any{
	(*QueryVerifierRequest)(nil),   // 0: contentgrid.verifiers.v1.QueryVerifierRequest
	(*QueryVerifierResponse)(nil),  // 1: contentgrid.verifiers.v1.QueryVerifierResponse
	(*QueryVerifiersRequest)(nil),  // 2: contentgrid.verifiers.v1.QueryVerifiersRequest
	(*QueryVerifiersResponse)(nil), // 3: contentgrid.verifiers.v1.QueryVerifiersResponse
	(*Verifier)(nil),               // 4: contentgrid.verifiers.v1.Verifier
}
var file_contentgrid_verifiers_v1_query_proto_depIdxs = []int32{
	4, // 0: contentgrid.verifiers.v1.QueryVerifierResponse.verifier:type_name -> contentgrid.verifiers.v1.Verifier
	4, // 1: contentgrid.verifiers.v1.QueryVerifiersResponse.verifiers:type_name -> contentgrid.verifiers.v1.Verifier
	0, // 2: contentgrid.verifiers.v1.Query.Verifier:input_type -> contentgrid.verifiers.v1.QueryVerifierRequest
	2, // 3: contentgrid.verifiers.v1.Query.Verifiers:input_type -> contentgrid.verifiers.v1.QueryVerifiersRequest
	1, // 4: contentgrid.verifiers.v1.Query.Verifier:output_type -> contentgrid.verifiers.v1.QueryVerifierResponse
	3, // 5: contentgrid.verifiers.v1.Query.Verifiers:output_type -> contentgrid.verifiers.v1.QueryVerifiersResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contentgrid_verifiers_v1_query_proto_init() }
func file_contentgrid_verifiers_v1_query_proto_init() {
	if File_contentgrid_verifiers_v1_query_proto != nil {
		return
	}
	file_contentgrid_verifiers_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_verifiers_v1_query_proto_rawDesc), len(file_contentgrid_verifiers_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contentgrid_verifiers_v1_query_proto_goTypes,
		DependencyIndexes: file_contentgrid_verifiers_v1_query_proto_depIdxs,
		MessageInfos:      file_contentgrid_verifiers_v1_query_proto_msgTypes,
	}.Build()
	File_contentgrid_verifiers_v1_query_proto = out.File
	file_contentgrid_verifiers_v1_query_proto_goTypes = nil
	file_contentgrid_verifiers_v1_query_proto_depIdxs = nil
}
