// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/verifiers/v1/tx.proto

package typespb

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgBond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifier      string                 `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBond) Reset() {
	*x = MsgBond{}
	mi := &file_contentgrid_verifiers_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBond) ProtoMessage() {}

func (x *MsgBond) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBond.ProtoReflect.Descriptor instead.
func (*MsgBond) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgBond) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *MsgBond) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgBond) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgBondResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifier      *Verifier              `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBondResponse) Reset() {
	*x = MsgBondResponse{}
	mi := &file_contentgrid_verifiers_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBondResponse) ProtoMessage() {}

func (x *MsgBondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBondResponse.ProtoReflect.Descriptor instead.
func (*MsgBondResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgBondResponse) GetVerifier() *Verifier {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type MsgUnbond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifier      string                 `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUnbond) Reset() {
	*x = MsgUnbond{}
	mi := &file_contentgrid_verifiers_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUnbond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUnbond) ProtoMessage() {}

func (x *MsgUnbond) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUnbond.ProtoReflect.Descriptor instead.
func (*MsgUnbond) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgUnbond) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *MsgUnbond) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgUnbond) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgUnbondResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verifier      *Verifier              `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUnbondResponse) Reset() {
	*x = MsgUnbondResponse{}
	mi := &file_contentgrid_verifiers_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUnbondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUnbondResponse) ProtoMessage() {}

func (x *MsgUnbondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUnbondResponse.ProtoReflect.Descriptor instead.
func (*MsgUnbondResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgUnbondResponse) GetVerifier() *Verifier {
	if x != nil {
		return x.Verifier
	}
	return nil
}

var File_contentgrid_verifiers_v1_tx_proto protoreflect.FileDescriptor

const file_contentgrid_verifiers_v1_tx_proto_rawDesc = "" +
	"\n" +
	"!contentgrid/verifiers/v1/tx.proto\x12\x18contentgrid.verifiers.v1\x1a$contentgrid/verifiers/v1/types.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\"b\n" +
	"\aMsgBond\x12\x1a\n" +
	"\bverifier\x18\x01 \x01(\tR\bverifier\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount:\r\x82\xe7\xb0*\bverifier\"Q\n" +
	"\x0fMsgBondResponse\x12>\n" +
	"\bverifier\x18\x01 \x01(\v2\".contentgrid.verifiers.v1.VerifierR\bverifier\"d\n" +
	"\tMsgUnbond\x12\x1a\n" +
	"\bverifier\x18\x01 \x01(\tR\bverifier\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount:\r\x82\xe7\xb0*\bverifier\"S\n" +
	"\x11MsgUnbondResponse\x12>\n" +
	"\bverifier\x18\x01 \x01(\v2\".contentgrid.verifiers.v1.VerifierR\bverifier2\xbe\x01\n" +
	"\x03Msg\x12T\n" +
	"\x04Bond\x12!.contentgrid.verifiers.v1.MsgBond\x1a).contentgrid.verifiers.v1.MsgBondResponse\x12Z\n" +
	"\x06Unbond\x12#.contentgrid.verifiers.v1.MsgUnbond\x1a+.contentgrid.verifiers.v1.MsgUnbondResponse\x1a\x05\x80\xe7\xb0*\x01B(Z&content-grid-chain/x/verifiers/typespbb\x06proto3"

var (
	file_contentgrid_verifiers_v1_tx_proto_rawDescOnce sync.Once
	file_contentgrid_verifiers_v1_tx_proto_rawDescData []byte
)

func file_contentgrid_verifiers_v1_tx_proto_rawDescGZIP() []byte {
	file_contentgrid_verifiers_v1_tx_proto_rawDescOnce.Do(func() {
		file_contentgrid_verifiers_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_verifiers_v1_tx_proto_rawDesc), len(file_contentgrid_verifiers_v1_tx_proto_rawDesc)))
	})
	return file_contentgrid_verifiers_v1_tx_proto_rawDescData
}

var file_contentgrid_verifiers_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contentgrid_verifiers_v1_tx_proto_goTypes = []any{
	(*MsgBond)(nil),           // 0: contentgrid.verifiers.v1.MsgBond
	(*MsgBondResponse)(nil),   // 1: contentgrid.verifiers.v1.MsgBondResponse
	(*MsgUnbond)(nil),         // 2: contentgrid.verifiers.v1.MsgUnbond
	(*MsgUnbondResponse)(nil), // 3: contentgrid.verifiers.v1.MsgUnbondResponse
	(*Verifier)(nil),          // 4: contentgrid.verifiers.v1.Verifier
}
var file_contentgrid_verifiers_v1_tx_proto_depIdxs = []int32{
	4, // 0: contentgrid.verifiers.v1.MsgBondResponse.verifier:type_name -> contentgrid.verifiers.v1.Verifier
	4, // 1: contentgrid.verifiers.v1.MsgUnbondResponse.verifier:type_name -> contentgrid.verifiers.v1.Verifier
	0, // 2: contentgrid.verifiers.v1.Msg.Bond:input_type -> contentgrid.verifiers.v1.MsgBond
	2, // 3: contentgrid.verifiers.v1.Msg.Unbond:input_type -> contentgrid.verifiers.v1.MsgUnbond
	1, // 4: contentgrid.verifiers.v1.Msg.Bond:output_type -> contentgrid.verifiers.v1.MsgBondResponse
	3, // 5: contentgrid.verifiers.v1.Msg.Unbond:output_type -> contentgrid.verifiers.v1.MsgUnbondResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contentgrid_verifiers_v1_tx_proto_init() }
func file_contentgrid_verifiers_v1_tx_proto_init() {
	if File_contentgrid_verifiers_v1_tx_proto != nil {
		return
	}
	file_contentgrid_verifiers_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_verifiers_v1_tx_proto_rawDesc), len(file_contentgrid_verifiers_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contentgrid_verifiers_v1_tx_proto_goTypes,
		DependencyIndexes: file_contentgrid_verifiers_v1_tx_proto_depIdxs,
		MessageInfos:      file_contentgrid_verifiers_v1_tx_proto_msgTypes,
	}.Build()
	File_contentgrid_verifiers_v1_tx_proto = out.File
	file_contentgrid_verifiers_v1_tx_proto_goTypes = nil
	file_contentgrid_verifiers_v1_tx_proto_depIdxs = nil
}
