// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/verifiers/v1/types.proto

package typespb

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifierStatus int32

const (
	VerifierStatus_VERIFIER_STATUS_UNSPECIFIED VerifierStatus = 0
	VerifierStatus_VERIFIER_STATUS_ACTIVE      VerifierStatus = 1
)

// Enum value maps for VerifierStatus.
var (
	VerifierStatus_name = map[int32]string{
		0: "VERIFIER_STATUS_UNSPECIFIED",
		1: "VERIFIER_STATUS_ACTIVE",
	}
	VerifierStatus_value = map[string]int32{
		"VERIFIER_STATUS_UNSPECIFIED": 0,
		"VERIFIER_STATUS_ACTIVE":      1,
	}
)

func (x VerifierStatus) Enum() *VerifierStatus {
	p := new(VerifierStatus)
	*p = x
	return p
}

func (x VerifierStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifierStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contentgrid_verifiers_v1_types_proto_enumTypes[0].Descriptor()
}

func (VerifierStatus) Type() protoreflect.EnumType {
	return &file_contentgrid_verifiers_v1_types_proto_enumTypes[0]
}

func (x VerifierStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifierStatus.Descriptor instead.
func (VerifierStatus) EnumDescriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_types_proto_rawDescGZIP(), []int{0}
}

type Verifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BondDenom     string                 `protobuf:"bytes,2,opt,name=bond_denom,json=bondDenom,proto3" json:"bond_denom,omitempty"`
	BondAmount    string                 `protobuf:"bytes,3,opt,name=bond_amount,json=bondAmount,proto3" json:"bond_amount,omitempty"`
	Status        VerifierStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=contentgrid.verifiers.v1.VerifierStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verifier) Reset() {
	*x = Verifier{}
	mi := &file_contentgrid_verifiers_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verifier) ProtoMessage() {}

func (x *Verifier) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_verifiers_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verifier.ProtoReflect.Descriptor instead.
func (*Verifier) Descriptor() ([]byte, []int) {
	return file_contentgrid_verifiers_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Verifier) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Verifier) GetBondDenom() string {
	if x != nil {
		return x.BondDenom
	}
	return ""
}

func (x *Verifier) GetBondAmount() string {
	if x != nil {
		return x.BondAmount
	}
	return ""
}

func (x *Verifier) GetStatus() VerifierStatus {
	if x != nil {
		return x.Status
	}
	return VerifierStatus_VERIFIER_STATUS_UNSPECIFIED
}

var File_contentgrid_verifiers_v1_types_proto protoreflect.FileDescriptor

const file_contentgrid_verifiers_v1_types_proto_rawDesc = "" +
	"\n" +
	"$contentgrid/verifiers/v1/types.proto\x12\x18contentgrid.verifiers.v1\x1a\x14gogoproto/gogo.proto\"\xa6\x01\n" +
	"\bVerifier\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"bond_denom\x18\x02 \x01(\tR\tbondDenom\x12\x1f\n" +
	"\vbond_amount\x18\x03 \x01(\tR\n" +
	"bondAmount\x12@\n" +
	"\x06status\x18\x04 \x01(\x0e2(.contentgrid.verifiers.v1.VerifierStatusR\x06status*M\n" +
	"\x0eVerifierStatus\x12\x1f\n" +
	"\x1bVERIFIER_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VERIFIER_STATUS_ACTIVE\x10\x01B(Z&content-grid-chain/x/verifiers/typespbb\x06proto3"

var (
	file_contentgrid_verifiers_v1_types_proto_rawDescOnce sync.Once
	file_contentgrid_verifiers_v1_types_proto_rawDescData []byte
)

func file_contentgrid_verifiers_v1_types_proto_rawDescGZIP() []byte {
	file_contentgrid_verifiers_v1_types_proto_rawDescOnce.Do(func() {
		file_contentgrid_verifiers_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_verifiers_v1_types_proto_rawDesc), len(file_contentgrid_verifiers_v1_types_proto_rawDesc)))
	})
	return file_contentgrid_verifiers_v1_types_proto_rawDescData
}

var file_contentgrid_verifiers_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contentgrid_verifiers_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contentgrid_verifiers_v1_types_proto_goTypes = []any{
	(VerifierStatus)(0), // 0: contentgrid.verifiers.v1.VerifierStatus
	(*Verifier)(nil),    // 1: contentgrid.verifiers.v1.Verifier
}
var file_contentgrid_verifiers_v1_types_proto_depIdxs = []int32{
	0, // 0: contentgrid.verifiers.v1.Verifier.status:type_name -> contentgrid.verifiers.v1.VerifierStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contentgrid_verifiers_v1_types_proto_init() }
func file_contentgrid_verifiers_v1_types_proto_init() {
	if File_contentgrid_verifiers_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_verifiers_v1_types_proto_rawDesc), len(file_contentgrid_verifiers_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contentgrid_verifiers_v1_types_proto_goTypes,
		DependencyIndexes: file_contentgrid_verifiers_v1_types_proto_depIdxs,
		EnumInfos:         file_contentgrid_verifiers_v1_types_proto_enumTypes,
		MessageInfos:      file_contentgrid_verifiers_v1_types_proto_msgTypes,
	}.Build()
	File_contentgrid_verifiers_v1_types_proto = out.File
	file_contentgrid_verifiers_v1_types_proto_goTypes = nil
	file_contentgrid_verifiers_v1_types_proto_depIdxs = nil
}
