syntax = "proto3";

package contentgrid.miners.v1;

import "contentgrid/miners/v1/types.proto";
import "cosmos/msg/v1/msg.proto";
import "gogoproto/gogo.proto";

option go_package = "content-grid-chain/x/miners/typespb";

service Msg {
  option (cosmos.msg.v1.service) = true;

  rpc RegisterMiner(MsgRegisterMiner) returns (MsgRegisterMinerResponse);
  rpc UpdateMiner(MsgUpdateMiner) returns (MsgUpdateMinerResponse);
  rpc UpdateMinerStake(MsgUpdateMinerStake) returns (MsgUpdateMinerStakeResponse);
}

message MsgRegisterMiner {
  option (cosmos.msg.v1.signer) = "operator";

  string operator = 1;
  string metadata_uri = 2;
  uint32 services = 3;
  string min_bid_denom = 4;
  string min_bid_amount = 5;
  string stake = 6;
}

message MsgRegisterMinerResponse {
  Miner miner = 1;
}

message MsgUpdateMiner {
  option (cosmos.msg.v1.signer) = "operator";

  string operator = 1;
  string metadata_uri = 2;
  uint32 services = 3;
  string min_bid_denom = 4;
  string min_bid_amount = 5;
}

message MsgUpdateMinerResponse {
  Miner miner = 1;
}

message MsgUpdateMinerStake {
  option (cosmos.msg.v1.signer) = "operator";

  string operator = 1;
  string stake_delta = 2;
  bool increase = 3;
}

message MsgUpdateMinerStakeResponse {
  Miner miner = 1;
}
