// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: contentgrid/registry/v1/query.proto

package typespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Publisher_FullMethodName             = "/contentgrid.registry.v1.Query/Publisher"
	Query_Publishers_FullMethodName            = "/contentgrid.registry.v1.Query/Publishers"
	Query_VerifierAssignments_FullMethodName   = "/contentgrid.registry.v1.Query/VerifierAssignments"
	Query_RoundMeta_FullMethodName             = "/contentgrid.registry.v1.Query/RoundMeta"
	Query_DrandBeacon_FullMethodName           = "/contentgrid.registry.v1.Query/DrandBeacon"
	Query_LatestDrandBeacon_FullMethodName     = "/contentgrid.registry.v1.Query/LatestDrandBeacon"
	Query_DrandRequirement_FullMethodName      = "/contentgrid.registry.v1.Query/DrandRequirement"
	Query_PublisherSimilarStats_FullMethodName = "/contentgrid.registry.v1.Query/PublisherSimilarStats"
	Query_Slots_FullMethodName                 = "/contentgrid.registry.v1.Query/Slots"
	Query_Leases_FullMethodName                = "/contentgrid.registry.v1.Query/Leases"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	Publisher(ctx context.Context, in *QueryPublisherRequest, opts ...grpc.CallOption) (*QueryPublisherResponse, error)
	Publishers(ctx context.Context, in *QueryPublishersRequest, opts ...grpc.CallOption) (*QueryPublishersResponse, error)
	VerifierAssignments(ctx context.Context, in *QueryVerifierAssignmentsRequest, opts ...grpc.CallOption) (*QueryVerifierAssignmentsResponse, error)
	RoundMeta(ctx context.Context, in *QueryRoundMetaRequest, opts ...grpc.CallOption) (*QueryRoundMetaResponse, error)
	DrandBeacon(ctx context.Context, in *QueryDrandBeaconRequest, opts ...grpc.CallOption) (*QueryDrandBeaconResponse, error)
	LatestDrandBeacon(ctx context.Context, in *QueryLatestDrandBeaconRequest, opts ...grpc.CallOption) (*QueryLatestDrandBeaconResponse, error)
	DrandRequirement(ctx context.Context, in *QueryDrandRequirementRequest, opts ...grpc.CallOption) (*QueryDrandRequirementResponse, error)
	// Latest similar-site verification settlement for a publisher.
	PublisherSimilarStats(ctx context.Context, in *QueryPublisherSimilarStatsRequest, opts ...grpc.CallOption) (*QueryPublisherSimilarStatsResponse, error)
	Slots(ctx context.Context, in *QuerySlotsRequest, opts ...grpc.CallOption) (*QuerySlotsResponse, error)
	Leases(ctx context.Context, in *QueryLeasesRequest, opts ...grpc.CallOption) (*QueryLeasesResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Publisher(ctx context.Context, in *QueryPublisherRequest, opts ...grpc.CallOption) (*QueryPublisherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPublisherResponse)
	err := c.cc.Invoke(ctx, Query_Publisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Publishers(ctx context.Context, in *QueryPublishersRequest, opts ...grpc.CallOption) (*QueryPublishersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPublishersResponse)
	err := c.cc.Invoke(ctx, Query_Publishers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifierAssignments(ctx context.Context, in *QueryVerifierAssignmentsRequest, opts ...grpc.CallOption) (*QueryVerifierAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVerifierAssignmentsResponse)
	err := c.cc.Invoke(ctx, Query_VerifierAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RoundMeta(ctx context.Context, in *QueryRoundMetaRequest, opts ...grpc.CallOption) (*QueryRoundMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRoundMetaResponse)
	err := c.cc.Invoke(ctx, Query_RoundMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DrandBeacon(ctx context.Context, in *QueryDrandBeaconRequest, opts ...grpc.CallOption) (*QueryDrandBeaconResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDrandBeaconResponse)
	err := c.cc.Invoke(ctx, Query_DrandBeacon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestDrandBeacon(ctx context.Context, in *QueryLatestDrandBeaconRequest, opts ...grpc.CallOption) (*QueryLatestDrandBeaconResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLatestDrandBeaconResponse)
	err := c.cc.Invoke(ctx, Query_LatestDrandBeacon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DrandRequirement(ctx context.Context, in *QueryDrandRequirementRequest, opts ...grpc.CallOption) (*QueryDrandRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDrandRequirementResponse)
	err := c.cc.Invoke(ctx, Query_DrandRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PublisherSimilarStats(ctx context.Context, in *QueryPublisherSimilarStatsRequest, opts ...grpc.CallOption) (*QueryPublisherSimilarStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPublisherSimilarStatsResponse)
	err := c.cc.Invoke(ctx, Query_PublisherSimilarStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Slots(ctx context.Context, in *QuerySlotsRequest, opts ...grpc.CallOption) (*QuerySlotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySlotsResponse)
	err := c.cc.Invoke(ctx, Query_Slots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Leases(ctx context.Context, in *QueryLeasesRequest, opts ...grpc.CallOption) (*QueryLeasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLeasesResponse)
	err := c.cc.Invoke(ctx, Query_Leases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	Publisher(context.Context, *QueryPublisherRequest) (*QueryPublisherResponse, error)
	Publishers(context.Context, *QueryPublishersRequest) (*QueryPublishersResponse, error)
	VerifierAssignments(context.Context, *QueryVerifierAssignmentsRequest) (*QueryVerifierAssignmentsResponse, error)
	RoundMeta(context.Context, *QueryRoundMetaRequest) (*QueryRoundMetaResponse, error)
	DrandBeacon(context.Context, *QueryDrandBeaconRequest) (*QueryDrandBeaconResponse, error)
	LatestDrandBeacon(context.Context, *QueryLatestDrandBeaconRequest) (*QueryLatestDrandBeaconResponse, error)
	DrandRequirement(context.Context, *QueryDrandRequirementRequest) (*QueryDrandRequirementResponse, error)
	// Latest similar-site verification settlement for a publisher.
	PublisherSimilarStats(context.Context, *QueryPublisherSimilarStatsRequest) (*QueryPublisherSimilarStatsResponse, error)
	Slots(context.Context, *QuerySlotsRequest) (*QuerySlotsResponse, error)
	Leases(context.Context, *QueryLeasesRequest) (*QueryLeasesResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Publisher(context.Context, *QueryPublisherRequest) (*QueryPublisherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publisher not implemented")
}
func (UnimplementedQueryServer) Publishers(context.Context, *QueryPublishersRequest) (*QueryPublishersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publishers not implemented")
}
func (UnimplementedQueryServer) VerifierAssignments(context.Context, *QueryVerifierAssignmentsRequest) (*QueryVerifierAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifierAssignments not implemented")
}
func (UnimplementedQueryServer) RoundMeta(context.Context, *QueryRoundMetaRequest) (*QueryRoundMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RoundMeta not implemented")
}
func (UnimplementedQueryServer) DrandBeacon(context.Context, *QueryDrandBeaconRequest) (*QueryDrandBeaconResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrandBeacon not implemented")
}
func (UnimplementedQueryServer) LatestDrandBeacon(context.Context, *QueryLatestDrandBeaconRequest) (*QueryLatestDrandBeaconResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LatestDrandBeacon not implemented")
}
func (UnimplementedQueryServer) DrandRequirement(context.Context, *QueryDrandRequirementRequest) (*QueryDrandRequirementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrandRequirement not implemented")
}
func (UnimplementedQueryServer) PublisherSimilarStats(context.Context, *QueryPublisherSimilarStatsRequest) (*QueryPublisherSimilarStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublisherSimilarStats not implemented")
}
func (UnimplementedQueryServer) Slots(context.Context, *QuerySlotsRequest) (*QuerySlotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Slots not implemented")
}
func (UnimplementedQueryServer) Leases(context.Context, *QueryLeasesRequest) (*QueryLeasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Leases not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Publisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Publisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Publisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Publisher(ctx, req.(*QueryPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Publishers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPublishersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Publishers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Publishers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Publishers(ctx, req.(*QueryPublishersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifierAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifierAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifierAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VerifierAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifierAssignments(ctx, req.(*QueryVerifierAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RoundMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRoundMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RoundMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_RoundMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RoundMeta(ctx, req.(*QueryRoundMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DrandBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDrandBeaconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DrandBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DrandBeacon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DrandBeacon(ctx, req.(*QueryDrandBeaconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestDrandBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestDrandBeaconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestDrandBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LatestDrandBeacon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestDrandBeacon(ctx, req.(*QueryLatestDrandBeaconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DrandRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDrandRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DrandRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DrandRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DrandRequirement(ctx, req.(*QueryDrandRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PublisherSimilarStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPublisherSimilarStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PublisherSimilarStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PublisherSimilarStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PublisherSimilarStats(ctx, req.(*QueryPublisherSimilarStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Slots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Slots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Slots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Slots(ctx, req.(*QuerySlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Leases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLeasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Leases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Leases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Leases(ctx, req.(*QueryLeasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contentgrid.registry.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publisher",
			Handler:    _Query_Publisher_Handler,
		},
		{
			MethodName: "Publishers",
			Handler:    _Query_Publishers_Handler,
		},
		{
			MethodName: "VerifierAssignments",
			Handler:    _Query_VerifierAssignments_Handler,
		},
		{
			MethodName: "RoundMeta",
			Handler:    _Query_RoundMeta_Handler,
		},
		{
			MethodName: "DrandBeacon",
			Handler:    _Query_DrandBeacon_Handler,
		},
		{
			MethodName: "LatestDrandBeacon",
			Handler:    _Query_LatestDrandBeacon_Handler,
		},
		{
			MethodName: "DrandRequirement",
			Handler:    _Query_DrandRequirement_Handler,
		},
		{
			MethodName: "PublisherSimilarStats",
			Handler:    _Query_PublisherSimilarStats_Handler,
		},
		{
			MethodName: "Slots",
			Handler:    _Query_Slots_Handler,
		},
		{
			MethodName: "Leases",
			Handler:    _Query_Leases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contentgrid/registry/v1/query.proto",
}
