// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/registry/v1/query.proto

package typespb

import (
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryPublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPublisherRequest) Reset() {
	*x = QueryPublisherRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPublisherRequest) ProtoMessage() {}

func (x *QueryPublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPublisherRequest.ProtoReflect.Descriptor instead.
func (*QueryPublisherRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryPublisherRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type QueryPublisherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Website       *Website               `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPublisherResponse) Reset() {
	*x = QueryPublisherResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPublisherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPublisherResponse) ProtoMessage() {}

func (x *QueryPublisherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPublisherResponse.ProtoReflect.Descriptor instead.
func (*QueryPublisherResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryPublisherResponse) GetWebsite() *Website {
	if x != nil {
		return x.Website
	}
	return nil
}

type QueryPublishersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPublishersRequest) Reset() {
	*x = QueryPublishersRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPublishersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPublishersRequest) ProtoMessage() {}

func (x *QueryPublishersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPublishersRequest.ProtoReflect.Descriptor instead.
func (*QueryPublishersRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPublishersRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryPublishersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Websites      []*Website             `protobuf:"bytes,1,rep,name=websites,proto3" json:"websites,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPublishersResponse) Reset() {
	*x = QueryPublishersResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPublishersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPublishersResponse) ProtoMessage() {}

func (x *QueryPublishersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPublishersResponse.ProtoReflect.Descriptor instead.
func (*QueryPublishersResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPublishersResponse) GetWebsites() []*Website {
	if x != nil {
		return x.Websites
	}
	return nil
}

func (x *QueryPublishersResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryVerifierAssignmentsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Verifier         string                 `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	IncludeFinalized bool                   `protobuf:"varint,2,opt,name=include_finalized,json=includeFinalized,proto3" json:"include_finalized,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryVerifierAssignmentsRequest) Reset() {
	*x = QueryVerifierAssignmentsRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVerifierAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVerifierAssignmentsRequest) ProtoMessage() {}

func (x *QueryVerifierAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVerifierAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*QueryVerifierAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryVerifierAssignmentsRequest) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *QueryVerifierAssignmentsRequest) GetIncludeFinalized() bool {
	if x != nil {
		return x.IncludeFinalized
	}
	return false
}

type QueryVerifierAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*VerifierAssignment  `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVerifierAssignmentsResponse) Reset() {
	*x = QueryVerifierAssignmentsResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVerifierAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVerifierAssignmentsResponse) ProtoMessage() {}

func (x *QueryVerifierAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVerifierAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*QueryVerifierAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryVerifierAssignmentsResponse) GetAssignments() []*VerifierAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type QueryRoundMetaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoundStartUnix int64                  `protobuf:"varint,1,opt,name=round_start_unix,json=roundStartUnix,proto3" json:"round_start_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRoundMetaRequest) Reset() {
	*x = QueryRoundMetaRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoundMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoundMetaRequest) ProtoMessage() {}

func (x *QueryRoundMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoundMetaRequest.ProtoReflect.Descriptor instead.
func (*QueryRoundMetaRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryRoundMetaRequest) GetRoundStartUnix() int64 {
	if x != nil {
		return x.RoundStartUnix
	}
	return 0
}

type QueryRoundMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *VerificationRoundMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoundMetaResponse) Reset() {
	*x = QueryRoundMetaResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoundMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoundMetaResponse) ProtoMessage() {}

func (x *QueryRoundMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoundMetaResponse.ProtoReflect.Descriptor instead.
func (*QueryRoundMetaResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRoundMetaResponse) GetMeta() *VerificationRoundMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type QueryDrandBeaconRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDrandBeaconRequest) Reset() {
	*x = QueryDrandBeaconRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDrandBeaconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDrandBeaconRequest) ProtoMessage() {}

func (x *QueryDrandBeaconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDrandBeaconRequest.ProtoReflect.Descriptor instead.
func (*QueryDrandBeaconRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryDrandBeaconRequest) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type QueryDrandBeaconResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beacon        *DrandBeacon           `protobuf:"bytes,1,opt,name=beacon,proto3" json:"beacon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDrandBeaconResponse) Reset() {
	*x = QueryDrandBeaconResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDrandBeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDrandBeaconResponse) ProtoMessage() {}

func (x *QueryDrandBeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDrandBeaconResponse.ProtoReflect.Descriptor instead.
func (*QueryDrandBeaconResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryDrandBeaconResponse) GetBeacon() *DrandBeacon {
	if x != nil {
		return x.Beacon
	}
	return nil
}

type QueryLatestDrandBeaconRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLatestDrandBeaconRequest) Reset() {
	*x = QueryLatestDrandBeaconRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLatestDrandBeaconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLatestDrandBeaconRequest) ProtoMessage() {}

func (x *QueryLatestDrandBeaconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLatestDrandBeaconRequest.ProtoReflect.Descriptor instead.
func (*QueryLatestDrandBeaconRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{10}
}

type QueryLatestDrandBeaconResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beacon        *DrandBeacon           `protobuf:"bytes,1,opt,name=beacon,proto3" json:"beacon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLatestDrandBeaconResponse) Reset() {
	*x = QueryLatestDrandBeaconResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLatestDrandBeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLatestDrandBeaconResponse) ProtoMessage() {}

func (x *QueryLatestDrandBeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLatestDrandBeaconResponse.ProtoReflect.Descriptor instead.
func (*QueryLatestDrandBeaconResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryLatestDrandBeaconResponse) GetBeacon() *DrandBeacon {
	if x != nil {
		return x.Beacon
	}
	return nil
}

type QueryPublisherSimilarStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPublisherSimilarStatsRequest) Reset() {
	*x = QueryPublisherSimilarStatsRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPublisherSimilarStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPublisherSimilarStatsRequest) ProtoMessage() {}

func (x *QueryPublisherSimilarStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPublisherSimilarStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryPublisherSimilarStatsRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *QueryPublisherSimilarStatsRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type QueryPublisherSimilarStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *PublisherSimilarStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPublisherSimilarStatsResponse) Reset() {
	*x = QueryPublisherSimilarStatsResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPublisherSimilarStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPublisherSimilarStatsResponse) ProtoMessage() {}

func (x *QueryPublisherSimilarStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPublisherSimilarStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryPublisherSimilarStatsResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryPublisherSimilarStatsResponse) GetStats() *PublisherSimilarStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type QuerySlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publisher     string                 `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Status        SlotStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=contentgrid.registry.v1.SlotStatus" json:"status,omitempty"`
	Pagination    *query.PageRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySlotsRequest) Reset() {
	*x = QuerySlotsRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySlotsRequest) ProtoMessage() {}

func (x *QuerySlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySlotsRequest.ProtoReflect.Descriptor instead.
func (*QuerySlotsRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *QuerySlotsRequest) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *QuerySlotsRequest) GetStatus() SlotStatus {
	if x != nil {
		return x.Status
	}
	return SlotStatus_SLOT_STATUS_UNSPECIFIED
}

func (x *QuerySlotsRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QuerySlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*Slot                `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySlotsResponse) Reset() {
	*x = QuerySlotsResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySlotsResponse) ProtoMessage() {}

func (x *QuerySlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySlotsResponse.ProtoReflect.Descriptor instead.
func (*QuerySlotsResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{15}
}

func (x *QuerySlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *QuerySlotsResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryLeasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publisher     string                 `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	SlotId        string                 `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,3,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	AtUnix        int64                  `protobuf:"varint,4,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	Pagination    *query.PageRequest     `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLeasesRequest) Reset() {
	*x = QueryLeasesRequest{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLeasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLeasesRequest) ProtoMessage() {}

func (x *QueryLeasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLeasesRequest.ProtoReflect.Descriptor instead.
func (*QueryLeasesRequest) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryLeasesRequest) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *QueryLeasesRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *QueryLeasesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *QueryLeasesRequest) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

func (x *QueryLeasesRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type QueryLeasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leases        []*SlotLease           `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLeasesResponse) Reset() {
	*x = QueryLeasesResponse{}
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLeasesResponse) ProtoMessage() {}

func (x *QueryLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLeasesResponse.ProtoReflect.Descriptor instead.
func (*QueryLeasesResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryLeasesResponse) GetLeases() []*SlotLease {
	if x != nil {
		return x.Leases
	}
	return nil
}

func (x *QueryLeasesResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_contentgrid_registry_v1_query_proto protoreflect.FileDescriptor

const file_contentgrid_registry_v1_query_proto_rawDesc = "" +
	"\n" +
	"#contentgrid/registry/v1/query.proto\x12\x17contentgrid.registry.v1\x1a#contentgrid/registry/v1/types.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"/\n" +
	"\x15QueryPublisherRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"T\n" +
	"\x16QueryPublisherResponse\x12:\n" +
	"\awebsite\x18\x01 \x01(\v2 .contentgrid.registry.v1.WebsiteR\awebsite\"`\n" +
	"\x16QueryPublishersRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xa0\x01\n" +
	"\x17QueryPublishersResponse\x12<\n" +
	"\bwebsites\x18\x01 \x03(\v2 .contentgrid.registry.v1.WebsiteR\bwebsites\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"j\n" +
	"\x1fQueryVerifierAssignmentsRequest\x12\x1a\n" +
	"\bverifier\x18\x01 \x01(\tR\bverifier\x12+\n" +
	"\x11include_finalized\x18\x02 \x01(\bR\x10includeFinalized\"q\n" +
	" QueryVerifierAssignmentsResponse\x12M\n" +
	"\vassignments\x18\x01 \x03(\v2+.contentgrid.registry.v1.VerifierAssignmentR\vassignments\"A\n" +
	"\x15QueryRoundMetaRequest\x12(\n" +
	"\x10round_start_unix\x18\x01 \x01(\x03R\x0eroundStartUnix\"\\\n" +
	"\x16QueryRoundMetaResponse\x12B\n" +
	"\x04meta\x18\x01 \x01(\v2..contentgrid.registry.v1.VerificationRoundMetaR\x04meta\"/\n" +
	"\x17QueryDrandBeaconRequest\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\"X\n" +
	"\x18QueryDrandBeaconResponse\x12<\n" +
	"\x06beacon\x18\x01 \x01(\v2$.contentgrid.registry.v1.DrandBeaconR\x06beacon\"\x1f\n" +
	"\x1dQueryLatestDrandBeaconRequest\"^\n" +
	"\x1eQueryLatestDrandBeaconResponse\x12<\n" +
	"\x06beacon\x18\x01 \x01(\v2$.contentgrid.registry.v1.DrandBeaconR\x06beacon\";\n" +
	"!QueryPublisherSimilarStatsRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"j\n" +
	"\"QueryPublisherSimilarStatsResponse\x12D\n" +
	"\x05stats\x18\x01 \x01(\v2..contentgrid.registry.v1.PublisherSimilarStatsR\x05stats\"\xb6\x01\n" +
	"\x11QuerySlotsRequest\x12\x1c\n" +
	"\tpublisher\x18\x01 \x01(\tR\tpublisher\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.contentgrid.registry.v1.SlotStatusR\x06status\x12F\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x92\x01\n" +
	"\x12QuerySlotsResponse\x123\n" +
	"\x05slots\x18\x01 \x03(\v2\x1d.contentgrid.registry.v1.SlotR\x05slots\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"\xcd\x01\n" +
	"\x12QueryLeasesRequest\x12\x1c\n" +
	"\tpublisher\x18\x01 \x01(\tR\tpublisher\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\tR\x06slotId\x12\x1f\n" +
	"\vactive_only\x18\x03 \x01(\bR\n" +
	"activeOnly\x12\x17\n" +
	"\aat_unix\x18\x04 \x01(\x03R\x06atUnix\x12F\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x9a\x01\n" +
	"\x13QueryLeasesResponse\x12:\n" +
	"\x06leases\x18\x01 \x03(\v2\".contentgrid.registry.v1.SlotLeaseR\x06leases\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination2\xa0\f\n" +
	"\x05Query\x12\xa3\x01\n" +
	"\tPublisher\x12..contentgrid.registry.v1.QueryPublisherRequest\x1a/.contentgrid.registry.v1.QueryPublisherResponse\"5\x82\xd3\xe4\x93\x02/\x12-/content-grid/registry/v1/publishers/{domain}\x12\x9d\x01\n" +
	"\n" +
	"Publishers\x12/.contentgrid.registry.v1.QueryPublishersRequest\x1a0.contentgrid.registry.v1.QueryPublishersResponse\",\x82\xd3\xe4\x93\x02&\x12$/content-grid/registry/v1/publishers\x12\xce\x01\n" +
	"\x13VerifierAssignments\x128.contentgrid.registry.v1.QueryVerifierAssignmentsRequest\x1a9.contentgrid.registry.v1.QueryVerifierAssignmentsResponse\"B\x82\xd3\xe4\x93\x02<\x12:/content-grid/registry/v1/verifiers/{verifier}/assignments\x12\xae\x01\n" +
	"\tRoundMeta\x12..contentgrid.registry.v1.QueryRoundMetaRequest\x1a/.contentgrid.registry.v1.QueryRoundMetaResponse\"@\x82\xd3\xe4\x93\x02:\x128/content-grid/registry/v1/rounds/{round_start_unix}/meta\x12\xa3\x01\n" +
	"\vDrandBeacon\x120.contentgrid.registry.v1.QueryDrandBeaconRequest\x1a1.contentgrid.registry.v1.QueryDrandBeaconResponse\"/\x82\xd3\xe4\x93\x02)\x12'/content-grid/registry/v1/drand/{round}\x12\xb4\x01\n" +
	"\x11LatestDrandBeacon\x126.contentgrid.registry.v1.QueryLatestDrandBeaconRequest\x1a7.contentgrid.registry.v1.QueryLatestDrandBeaconResponse\".\x82\xd3\xe4\x93\x02(\x12&/content-grid/registry/v1/drand/latest\x12\xd5\x01\n" +
	"\x15PublisherSimilarStats\x12:.contentgrid.registry.v1.QueryPublisherSimilarStatsRequest\x1a;.contentgrid.registry.v1.QueryPublisherSimilarStatsResponse\"C\x82\xd3\xe4\x93\x02=\x12;/content-grid/registry/v1/publishers/{domain}/similar-stats\x12\x89\x01\n" +
	"\x05Slots\x12*.contentgrid.registry.v1.QuerySlotsRequest\x1a+.contentgrid.registry.v1.QuerySlotsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/content-grid/registry/v1/slots\x12\x8d\x01\n" +
	"\x06Leases\x12+.contentgrid.registry.v1.QueryLeasesRequest\x1a,.contentgrid.registry.v1.QueryLeasesResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /content-grid/registry/v1/leasesB'Z%content-grid-chain/x/registry/typespbb\x06proto3"

var (
	file_contentgrid_registry_v1_query_proto_rawDescOnce sync.Once
	file_contentgrid_registry_v1_query_proto_rawDescData []byte
)

func file_contentgrid_registry_v1_query_proto_rawDescGZIP() []byte {
	file_contentgrid_registry_v1_query_proto_rawDescOnce.Do(func() {
		file_contentgrid_registry_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_registry_v1_query_proto_rawDesc), len(file_contentgrid_registry_v1_query_proto_rawDesc)))
	})
	return file_contentgrid_registry_v1_query_proto_rawDescData
}

var file_contentgrid_registry_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_contentgrid_registry_v1_query_proto_goTypes = []any{
	(*QueryPublisherRequest)(nil),              // 0: contentgrid.registry.v1.QueryPublisherRequest
	(*QueryPublisherResponse)(nil),             // 1: contentgrid.registry.v1.QueryPublisherResponse
	(*QueryPublishersRequest)(nil),             // 2: contentgrid.registry.v1.QueryPublishersRequest
	(*QueryPublishersResponse)(nil),            // 3: contentgrid.registry.v1.QueryPublishersResponse
	(*QueryVerifierAssignmentsRequest)(nil),    // 4: contentgrid.registry.v1.QueryVerifierAssignmentsRequest
	(*QueryVerifierAssignmentsResponse)(nil),   // 5: contentgrid.registry.v1.QueryVerifierAssignmentsResponse
	(*QueryRoundMetaRequest)(nil),              // 6: contentgrid.registry.v1.QueryRoundMetaRequest
	(*QueryRoundMetaResponse)(nil),             // 7: contentgrid.registry.v1.QueryRoundMetaResponse
	(*QueryDrandBeaconRequest)(nil),            // 8: contentgrid.registry.v1.QueryDrandBeaconRequest
	(*QueryDrandBeaconResponse)(nil),           // 9: contentgrid.registry.v1.QueryDrandBeaconResponse
	(*QueryLatestDrandBeaconRequest)(nil),      // 10: contentgrid.registry.v1.QueryLatestDrandBeaconRequest
	(*QueryLatestDrandBeaconResponse)(nil),     // 11: contentgrid.registry.v1.QueryLatestDrandBeaconResponse
	(*QueryPublisherSimilarStatsRequest)(nil),  // 12: contentgrid.registry.v1.QueryPublisherSimilarStatsRequest
	(*QueryPublisherSimilarStatsResponse)(nil), // 13: contentgrid.registry.v1.QueryPublisherSimilarStatsResponse
	(*QuerySlotsRequest)(nil),                  // 14: contentgrid.registry.v1.QuerySlotsRequest
	(*QuerySlotsResponse)(nil),                 // 15: contentgrid.registry.v1.QuerySlotsResponse
	(*QueryLeasesRequest)(nil),                 // 16: contentgrid.registry.v1.QueryLeasesRequest
	(*QueryLeasesResponse)(nil),                // 17: contentgrid.registry.v1.QueryLeasesResponse
	(*Website)(nil),                            // 18: contentgrid.registry.v1.Website
	(*query.PageRequest)(nil),                  // 19: cosmos.base.query.v1beta1.PageRequest
	(*query.PageResponse)(nil),                 // 20: cosmos.base.query.v1beta1.PageResponse
	(*VerifierAssignment)(nil),                 // 21: contentgrid.registry.v1.VerifierAssignment
	(*VerificationRoundMeta)(nil),              // 22: contentgrid.registry.v1.VerificationRoundMeta
	(*DrandBeacon)(nil),                        // 23: contentgrid.registry.v1.DrandBeacon
	(*PublisherSimilarStats)(nil),              // 24: contentgrid.registry.v1.PublisherSimilarStats
	(SlotStatus)(0),                            // 25: contentgrid.registry.v1.SlotStatus
	(*Slot)(nil),                               // 26: contentgrid.registry.v1.Slot
	(*SlotLease)(nil),                          // 27: contentgrid.registry.v1.SlotLease
}
var file_contentgrid_registry_v1_query_proto_depIdxs = []int32{
	18, // 0: contentgrid.registry.v1.QueryPublisherResponse.website:type_name -> contentgrid.registry.v1.Website
	19, // 1: contentgrid.registry.v1.QueryPublishersRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	18, // 2: contentgrid.registry.v1.QueryPublishersResponse.websites:type_name -> contentgrid.registry.v1.Website
	20, // 3: contentgrid.registry.v1.QueryPublishersResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	21, // 4: contentgrid.registry.v1.QueryVerifierAssignmentsResponse.assignments:type_name -> contentgrid.registry.v1.VerifierAssignment
	22, // 5: contentgrid.registry.v1.QueryRoundMetaResponse.meta:type_name -> contentgrid.registry.v1.VerificationRoundMeta
	23, // 6: contentgrid.registry.v1.QueryDrandBeaconResponse.beacon:type_name -> contentgrid.registry.v1.DrandBeacon
	23, // 7: contentgrid.registry.v1.QueryLatestDrandBeaconResponse.beacon:type_name -> contentgrid.registry.v1.DrandBeacon
	24, // 8: contentgrid.registry.v1.QueryPublisherSimilarStatsResponse.stats:type_name -> contentgrid.registry.v1.PublisherSimilarStats
	25, // 9: contentgrid.registry.v1.QuerySlotsRequest.status:type_name -> contentgrid.registry.v1.SlotStatus
	19, // 10: contentgrid.registry.v1.QuerySlotsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	26, // 11: contentgrid.registry.v1.QuerySlotsResponse.slots:type_name -> contentgrid.registry.v1.Slot
	20, // 12: contentgrid.registry.v1.QuerySlotsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	19, // 13: contentgrid.registry.v1.QueryLeasesRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	27, // 14: contentgrid.registry.v1.QueryLeasesResponse.leases:type_name -> contentgrid.registry.v1.SlotLease
	20, // 15: contentgrid.registry.v1.QueryLeasesResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	0,  // 16: contentgrid.registry.v1.Query.Publisher:input_type -> contentgrid.registry.v1.QueryPublisherRequest
	2,  // 17: contentgrid.registry.v1.Query.Publishers:input_type -> contentgrid.registry.v1.QueryPublishersRequest
	4,  // 18: contentgrid.registry.v1.Query.VerifierAssignments:input_type -> contentgrid.registry.v1.QueryVerifierAssignmentsRequest
	6,  // 19: contentgrid.registry.v1.Query.RoundMeta:input_type -> contentgrid.registry.v1.QueryRoundMetaRequest
	8,  // 20: contentgrid.registry.v1.Query.DrandBeacon:input_type -> contentgrid.registry.v1.QueryDrandBeaconRequest
	10, // 21: contentgrid.registry.v1.Query.LatestDrandBeacon:input_type -> contentgrid.registry.v1.QueryLatestDrandBeaconRequest
	12, // 22: contentgrid.registry.v1.Query.PublisherSimilarStats:input_type -> contentgrid.registry.v1.QueryPublisherSimilarStatsRequest
	14, // 23: contentgrid.registry.v1.Query.Slots:input_type -> contentgrid.registry.v1.QuerySlotsRequest
	16, // 24: contentgrid.registry.v1.Query.Leases:input_type -> contentgrid.registry.v1.QueryLeasesRequest
	1,  // 25: contentgrid.registry.v1.Query.Publisher:output_type -> contentgrid.registry.v1.QueryPublisherResponse
	3,  // 26: contentgrid.registry.v1.Query.Publishers:output_type -> contentgrid.registry.v1.QueryPublishersResponse
	5,  // 27: contentgrid.registry.v1.Query.VerifierAssignments:output_type -> contentgrid.registry.v1.QueryVerifierAssignmentsResponse
	7,  // 28: contentgrid.registry.v1.Query.RoundMeta:output_type -> contentgrid.registry.v1.QueryRoundMetaResponse
	9,  // 29: contentgrid.registry.v1.Query.DrandBeacon:output_type -> contentgrid.registry.v1.QueryDrandBeaconResponse
	11, // 30: contentgrid.registry.v1.Query.LatestDrandBeacon:output_type -> contentgrid.registry.v1.QueryLatestDrandBeaconResponse
	13, // 31: contentgrid.registry.v1.Query.PublisherSimilarStats:output_type -> contentgrid.registry.v1.QueryPublisherSimilarStatsResponse
	15, // 32: contentgrid.registry.v1.Query.Slots:output_type -> contentgrid.registry.v1.QuerySlotsResponse
	17, // 33: contentgrid.registry.v1.Query.Leases:output_type -> contentgrid.registry.v1.QueryLeasesResponse
	25, // [25:34] is the sub-list for method output_type
	16, // [16:25] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_contentgrid_registry_v1_query_proto_init() }
func file_contentgrid_registry_v1_query_proto_init() {
	if File_contentgrid_registry_v1_query_proto != nil {
		return
	}
	file_contentgrid_registry_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_registry_v1_query_proto_rawDesc), len(file_contentgrid_registry_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contentgrid_registry_v1_query_proto_goTypes,
		DependencyIndexes: file_contentgrid_registry_v1_query_proto_depIdxs,
		MessageInfos:      file_contentgrid_registry_v1_query_proto_msgTypes,
	}.Build()
	File_contentgrid_registry_v1_query_proto = out.File
	file_contentgrid_registry_v1_query_proto_goTypes = nil
	file_contentgrid_registry_v1_query_proto_depIdxs = nil
}
