// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/registry/v1/tx.proto

package typespb

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgRegisterPublisher struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Owner       string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Domain      string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	MetadataUri string                 `protobuf:"bytes,3,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	Proof       string                 `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	Verifier    string                 `protobuf:"bytes,5,opt,name=verifier,proto3" json:"verifier,omitempty"`
	// Optional referrer address (intended for verifier referral incentives).
	Referrer      string `protobuf:"bytes,6,opt,name=referrer,proto3" json:"referrer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterPublisher) Reset() {
	*x = MsgRegisterPublisher{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterPublisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterPublisher) ProtoMessage() {}

func (x *MsgRegisterPublisher) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterPublisher.ProtoReflect.Descriptor instead.
func (*MsgRegisterPublisher) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgRegisterPublisher) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgRegisterPublisher) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MsgRegisterPublisher) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *MsgRegisterPublisher) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *MsgRegisterPublisher) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *MsgRegisterPublisher) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

type MsgRegisterPublisherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Website       *Website               `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterPublisherResponse) Reset() {
	*x = MsgRegisterPublisherResponse{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterPublisherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterPublisherResponse) ProtoMessage() {}

func (x *MsgRegisterPublisherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterPublisherResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterPublisherResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgRegisterPublisherResponse) GetWebsite() *Website {
	if x != nil {
		return x.Website
	}
	return nil
}

type MsgSubmitVerificationCommit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Verifier       string                 `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	Domain         string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	RoundStartUnix int64                  `protobuf:"varint,3,opt,name=round_start_unix,json=roundStartUnix,proto3" json:"round_start_unix,omitempty"`
	CommitHash     string                 `protobuf:"bytes,4,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgSubmitVerificationCommit) Reset() {
	*x = MsgSubmitVerificationCommit{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitVerificationCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitVerificationCommit) ProtoMessage() {}

func (x *MsgSubmitVerificationCommit) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitVerificationCommit.ProtoReflect.Descriptor instead.
func (*MsgSubmitVerificationCommit) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgSubmitVerificationCommit) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *MsgSubmitVerificationCommit) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MsgSubmitVerificationCommit) GetRoundStartUnix() int64 {
	if x != nil {
		return x.RoundStartUnix
	}
	return 0
}

func (x *MsgSubmitVerificationCommit) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

type MsgSubmitVerificationCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitVerificationCommitResponse) Reset() {
	*x = MsgSubmitVerificationCommitResponse{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitVerificationCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitVerificationCommitResponse) ProtoMessage() {}

func (x *MsgSubmitVerificationCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitVerificationCommitResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitVerificationCommitResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgRevealVerification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Verifier       string                 `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	Domain         string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	RoundStartUnix int64                  `protobuf:"varint,3,opt,name=round_start_unix,json=roundStartUnix,proto3" json:"round_start_unix,omitempty"`
	// Verification result: true = pass, false = fail.
	Passed bool `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	// Optional evidence hash (must match commit if provided).
	EvidenceHash string `protobuf:"bytes,5,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	// Nonce used to bind the commit hash.
	Nonce         string `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevealVerification) Reset() {
	*x = MsgRevealVerification{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealVerification) ProtoMessage() {}

func (x *MsgRevealVerification) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealVerification.ProtoReflect.Descriptor instead.
func (*MsgRevealVerification) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgRevealVerification) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *MsgRevealVerification) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MsgRevealVerification) GetRoundStartUnix() int64 {
	if x != nil {
		return x.RoundStartUnix
	}
	return 0
}

func (x *MsgRevealVerification) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *MsgRevealVerification) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

func (x *MsgRevealVerification) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type MsgRevealVerificationResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Submission    *PublisherVerificationSubmission `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevealVerificationResponse) Reset() {
	*x = MsgRevealVerificationResponse{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealVerificationResponse) ProtoMessage() {}

func (x *MsgRevealVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealVerificationResponse.ProtoReflect.Descriptor instead.
func (*MsgRevealVerificationResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgRevealVerificationResponse) GetSubmission() *PublisherVerificationSubmission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type MsgCreateSlot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Publisher          string                 `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Domain             string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Label              string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Summary            string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Category           string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Placement          string                 `protobuf:"bytes,6,opt,name=placement,proto3" json:"placement,omitempty"`
	Size               string                 `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	RateDenom          string                 `protobuf:"bytes,8,opt,name=rate_denom,json=rateDenom,proto3" json:"rate_denom,omitempty"`
	RateAmount         string                 `protobuf:"bytes,9,opt,name=rate_amount,json=rateAmount,proto3" json:"rate_amount,omitempty"`
	UnitSeconds        int64                  `protobuf:"varint,10,opt,name=unit_seconds,json=unitSeconds,proto3" json:"unit_seconds,omitempty"`
	MinDurationSeconds int64                  `protobuf:"varint,11,opt,name=min_duration_seconds,json=minDurationSeconds,proto3" json:"min_duration_seconds,omitempty"`
	MaxDurationSeconds int64                  `protobuf:"varint,12,opt,name=max_duration_seconds,json=maxDurationSeconds,proto3" json:"max_duration_seconds,omitempty"`
	Tags               []string               `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MsgCreateSlot) Reset() {
	*x = MsgCreateSlot{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateSlot) ProtoMessage() {}

func (x *MsgCreateSlot) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateSlot.ProtoReflect.Descriptor instead.
func (*MsgCreateSlot) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgCreateSlot) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *MsgCreateSlot) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MsgCreateSlot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MsgCreateSlot) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *MsgCreateSlot) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MsgCreateSlot) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

func (x *MsgCreateSlot) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *MsgCreateSlot) GetRateDenom() string {
	if x != nil {
		return x.RateDenom
	}
	return ""
}

func (x *MsgCreateSlot) GetRateAmount() string {
	if x != nil {
		return x.RateAmount
	}
	return ""
}

func (x *MsgCreateSlot) GetUnitSeconds() int64 {
	if x != nil {
		return x.UnitSeconds
	}
	return 0
}

func (x *MsgCreateSlot) GetMinDurationSeconds() int64 {
	if x != nil {
		return x.MinDurationSeconds
	}
	return 0
}

func (x *MsgCreateSlot) GetMaxDurationSeconds() int64 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

func (x *MsgCreateSlot) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type MsgCreateSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *Slot                  `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateSlotResponse) Reset() {
	*x = MsgCreateSlotResponse{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateSlotResponse) ProtoMessage() {}

func (x *MsgCreateSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateSlotResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateSlotResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgCreateSlotResponse) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

type MsgUpdateSlotStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publisher     string                 `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	SlotId        string                 `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status        SlotStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=contentgrid.registry.v1.SlotStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateSlotStatus) Reset() {
	*x = MsgUpdateSlotStatus{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateSlotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateSlotStatus) ProtoMessage() {}

func (x *MsgUpdateSlotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateSlotStatus.ProtoReflect.Descriptor instead.
func (*MsgUpdateSlotStatus) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgUpdateSlotStatus) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *MsgUpdateSlotStatus) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *MsgUpdateSlotStatus) GetStatus() SlotStatus {
	if x != nil {
		return x.Status
	}
	return SlotStatus_SLOT_STATUS_UNSPECIFIED
}

type MsgUpdateSlotStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *Slot                  `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateSlotStatusResponse) Reset() {
	*x = MsgUpdateSlotStatusResponse{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateSlotStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateSlotStatusResponse) ProtoMessage() {}

func (x *MsgUpdateSlotStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateSlotStatusResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateSlotStatusResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *MsgUpdateSlotStatusResponse) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

type MsgLeaseSlot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Lessee          string                 `protobuf:"bytes,1,opt,name=lessee,proto3" json:"lessee,omitempty"`
	SlotId          string                 `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	TargetUrl       string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	StartsAtUnix    int64                  `protobuf:"varint,4,opt,name=starts_at_unix,json=startsAtUnix,proto3" json:"starts_at_unix,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MsgLeaseSlot) Reset() {
	*x = MsgLeaseSlot{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgLeaseSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLeaseSlot) ProtoMessage() {}

func (x *MsgLeaseSlot) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLeaseSlot.ProtoReflect.Descriptor instead.
func (*MsgLeaseSlot) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgLeaseSlot) GetLessee() string {
	if x != nil {
		return x.Lessee
	}
	return ""
}

func (x *MsgLeaseSlot) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *MsgLeaseSlot) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *MsgLeaseSlot) GetStartsAtUnix() int64 {
	if x != nil {
		return x.StartsAtUnix
	}
	return 0
}

func (x *MsgLeaseSlot) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type MsgLeaseSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *SlotLease             `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgLeaseSlotResponse) Reset() {
	*x = MsgLeaseSlotResponse{}
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgLeaseSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLeaseSlotResponse) ProtoMessage() {}

func (x *MsgLeaseSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLeaseSlotResponse.ProtoReflect.Descriptor instead.
func (*MsgLeaseSlotResponse) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_tx_proto_rawDescGZIP(), []int{11}
}

func (x *MsgLeaseSlotResponse) GetLease() *SlotLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

var File_contentgrid_registry_v1_tx_proto protoreflect.FileDescriptor

const file_contentgrid_registry_v1_tx_proto_rawDesc = "" +
	"\n" +
	" contentgrid/registry/v1/tx.proto\x12\x17contentgrid.registry.v1\x1a#contentgrid/registry/v1/types.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\"\xc1\x01\n" +
	"\x14MsgRegisterPublisher\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12!\n" +
	"\fmetadata_uri\x18\x03 \x01(\tR\vmetadataUri\x12\x14\n" +
	"\x05proof\x18\x04 \x01(\tR\x05proof\x12\x1a\n" +
	"\bverifier\x18\x05 \x01(\tR\bverifier\x12\x1a\n" +
	"\breferrer\x18\x06 \x01(\tR\breferrer:\n" +
	"\x82\xe7\xb0*\x05owner\"Z\n" +
	"\x1cMsgRegisterPublisherResponse\x12:\n" +
	"\awebsite\x18\x01 \x01(\v2 .contentgrid.registry.v1.WebsiteR\awebsite\"\xab\x01\n" +
	"\x1bMsgSubmitVerificationCommit\x12\x1a\n" +
	"\bverifier\x18\x01 \x01(\tR\bverifier\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12(\n" +
	"\x10round_start_unix\x18\x03 \x01(\x03R\x0eroundStartUnix\x12\x1f\n" +
	"\vcommit_hash\x18\x04 \x01(\tR\n" +
	"commitHash:\r\x82\xe7\xb0*\bverifier\"%\n" +
	"#MsgSubmitVerificationCommitResponse\"\xd7\x01\n" +
	"\x15MsgRevealVerification\x12\x1a\n" +
	"\bverifier\x18\x01 \x01(\tR\bverifier\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12(\n" +
	"\x10round_start_unix\x18\x03 \x01(\x03R\x0eroundStartUnix\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12#\n" +
	"\revidence_hash\x18\x05 \x01(\tR\fevidenceHash\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce:\r\x82\xe7\xb0*\bverifier\"y\n" +
	"\x1dMsgRevealVerificationResponse\x12X\n" +
	"\n" +
	"submission\x18\x01 \x01(\v28.contentgrid.registry.v1.PublisherVerificationSubmissionR\n" +
	"submission\"\xae\x03\n" +
	"\rMsgCreateSlot\x12\x1c\n" +
	"\tpublisher\x18\x01 \x01(\tR\tpublisher\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1c\n" +
	"\tplacement\x18\x06 \x01(\tR\tplacement\x12\x12\n" +
	"\x04size\x18\a \x01(\tR\x04size\x12\x1d\n" +
	"\n" +
	"rate_denom\x18\b \x01(\tR\trateDenom\x12\x1f\n" +
	"\vrate_amount\x18\t \x01(\tR\n" +
	"rateAmount\x12!\n" +
	"\funit_seconds\x18\n" +
	" \x01(\x03R\vunitSeconds\x120\n" +
	"\x14min_duration_seconds\x18\v \x01(\x03R\x12minDurationSeconds\x120\n" +
	"\x14max_duration_seconds\x18\f \x01(\x03R\x12maxDurationSeconds\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags:\x0e\x82\xe7\xb0*\tpublisher\"J\n" +
	"\x15MsgCreateSlotResponse\x121\n" +
	"\x04slot\x18\x01 \x01(\v2\x1d.contentgrid.registry.v1.SlotR\x04slot\"\x99\x01\n" +
	"\x13MsgUpdateSlotStatus\x12\x1c\n" +
	"\tpublisher\x18\x01 \x01(\tR\tpublisher\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\tR\x06slotId\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.contentgrid.registry.v1.SlotStatusR\x06status:\x0e\x82\xe7\xb0*\tpublisher\"P\n" +
	"\x1bMsgUpdateSlotStatusResponse\x121\n" +
	"\x04slot\x18\x01 \x01(\v2\x1d.contentgrid.registry.v1.SlotR\x04slot\"\xbc\x01\n" +
	"\fMsgLeaseSlot\x12\x16\n" +
	"\x06lessee\x18\x01 \x01(\tR\x06lessee\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12$\n" +
	"\x0estarts_at_unix\x18\x04 \x01(\x03R\fstartsAtUnix\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x03R\x0fdurationSeconds:\v\x82\xe7\xb0*\x06lessee\"P\n" +
	"\x14MsgLeaseSlotResponse\x128\n" +
	"\x05lease\x18\x01 \x01(\v2\".contentgrid.registry.v1.SlotLeaseR\x05lease2\xd7\x05\n" +
	"\x03Msg\x12y\n" +
	"\x11RegisterPublisher\x12-.contentgrid.registry.v1.MsgRegisterPublisher\x1a5.contentgrid.registry.v1.MsgRegisterPublisherResponse\x12\x8e\x01\n" +
	"\x18SubmitVerificationCommit\x124.contentgrid.registry.v1.MsgSubmitVerificationCommit\x1a<.contentgrid.registry.v1.MsgSubmitVerificationCommitResponse\x12|\n" +
	"\x12RevealVerification\x12..contentgrid.registry.v1.MsgRevealVerification\x1a6.contentgrid.registry.v1.MsgRevealVerificationResponse\x12d\n" +
	"\n" +
	"CreateSlot\x12&.contentgrid.registry.v1.MsgCreateSlot\x1a..contentgrid.registry.v1.MsgCreateSlotResponse\x12v\n" +
	"\x10UpdateSlotStatus\x12,.contentgrid.registry.v1.MsgUpdateSlotStatus\x1a4.contentgrid.registry.v1.MsgUpdateSlotStatusResponse\x12a\n" +
	"\tLeaseSlot\x12%.contentgrid.registry.v1.MsgLeaseSlot\x1a-.contentgrid.registry.v1.MsgLeaseSlotResponse\x1a\x05\x80\xe7\xb0*\x01B'Z%content-grid-chain/x/registry/typespbb\x06proto3"

var (
	file_contentgrid_registry_v1_tx_proto_rawDescOnce sync.Once
	file_contentgrid_registry_v1_tx_proto_rawDescData []byte
)

func file_contentgrid_registry_v1_tx_proto_rawDescGZIP() []byte {
	file_contentgrid_registry_v1_tx_proto_rawDescOnce.Do(func() {
		file_contentgrid_registry_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_registry_v1_tx_proto_rawDesc), len(file_contentgrid_registry_v1_tx_proto_rawDesc)))
	})
	return file_contentgrid_registry_v1_tx_proto_rawDescData
}

var file_contentgrid_registry_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_contentgrid_registry_v1_tx_proto_goTypes = []any{
	(*MsgRegisterPublisher)(nil),                // 0: contentgrid.registry.v1.MsgRegisterPublisher
	(*MsgRegisterPublisherResponse)(nil),        // 1: contentgrid.registry.v1.MsgRegisterPublisherResponse
	(*MsgSubmitVerificationCommit)(nil),         // 2: contentgrid.registry.v1.MsgSubmitVerificationCommit
	(*MsgSubmitVerificationCommitResponse)(nil), // 3: contentgrid.registry.v1.MsgSubmitVerificationCommitResponse
	(*MsgRevealVerification)(nil),               // 4: contentgrid.registry.v1.MsgRevealVerification
	(*MsgRevealVerificationResponse)(nil),       // 5: contentgrid.registry.v1.MsgRevealVerificationResponse
	(*MsgCreateSlot)(nil),                       // 6: contentgrid.registry.v1.MsgCreateSlot
	(*MsgCreateSlotResponse)(nil),               // 7: contentgrid.registry.v1.MsgCreateSlotResponse
	(*MsgUpdateSlotStatus)(nil),                 // 8: contentgrid.registry.v1.MsgUpdateSlotStatus
	(*MsgUpdateSlotStatusResponse)(nil),         // 9: contentgrid.registry.v1.MsgUpdateSlotStatusResponse
	(*MsgLeaseSlot)(nil),                        // 10: contentgrid.registry.v1.MsgLeaseSlot
	(*MsgLeaseSlotResponse)(nil),                // 11: contentgrid.registry.v1.MsgLeaseSlotResponse
	(*Website)(nil),                             // 12: contentgrid.registry.v1.Website
	(*PublisherVerificationSubmission)(nil),     // 13: contentgrid.registry.v1.PublisherVerificationSubmission
	(*Slot)(nil),                                // 14: contentgrid.registry.v1.Slot
	(SlotStatus)(0),                             // 15: contentgrid.registry.v1.SlotStatus
	(*SlotLease)(nil),                           // 16: contentgrid.registry.v1.SlotLease
}
var file_contentgrid_registry_v1_tx_proto_depIdxs = []int32{
	12, // 0: contentgrid.registry.v1.MsgRegisterPublisherResponse.website:type_name -> contentgrid.registry.v1.Website
	13, // 1: contentgrid.registry.v1.MsgRevealVerificationResponse.submission:type_name -> contentgrid.registry.v1.PublisherVerificationSubmission
	14, // 2: contentgrid.registry.v1.MsgCreateSlotResponse.slot:type_name -> contentgrid.registry.v1.Slot
	15, // 3: contentgrid.registry.v1.MsgUpdateSlotStatus.status:type_name -> contentgrid.registry.v1.SlotStatus
	14, // 4: contentgrid.registry.v1.MsgUpdateSlotStatusResponse.slot:type_name -> contentgrid.registry.v1.Slot
	16, // 5: contentgrid.registry.v1.MsgLeaseSlotResponse.lease:type_name -> contentgrid.registry.v1.SlotLease
	0,  // 6: contentgrid.registry.v1.Msg.RegisterPublisher:input_type -> contentgrid.registry.v1.MsgRegisterPublisher
	2,  // 7: contentgrid.registry.v1.Msg.SubmitVerificationCommit:input_type -> contentgrid.registry.v1.MsgSubmitVerificationCommit
	4,  // 8: contentgrid.registry.v1.Msg.RevealVerification:input_type -> contentgrid.registry.v1.MsgRevealVerification
	6,  // 9: contentgrid.registry.v1.Msg.CreateSlot:input_type -> contentgrid.registry.v1.MsgCreateSlot
	8,  // 10: contentgrid.registry.v1.Msg.UpdateSlotStatus:input_type -> contentgrid.registry.v1.MsgUpdateSlotStatus
	10, // 11: contentgrid.registry.v1.Msg.LeaseSlot:input_type -> contentgrid.registry.v1.MsgLeaseSlot
	1,  // 12: contentgrid.registry.v1.Msg.RegisterPublisher:output_type -> contentgrid.registry.v1.MsgRegisterPublisherResponse
	3,  // 13: contentgrid.registry.v1.Msg.SubmitVerificationCommit:output_type -> contentgrid.registry.v1.MsgSubmitVerificationCommitResponse
	5,  // 14: contentgrid.registry.v1.Msg.RevealVerification:output_type -> contentgrid.registry.v1.MsgRevealVerificationResponse
	7,  // 15: contentgrid.registry.v1.Msg.CreateSlot:output_type -> contentgrid.registry.v1.MsgCreateSlotResponse
	9,  // 16: contentgrid.registry.v1.Msg.UpdateSlotStatus:output_type -> contentgrid.registry.v1.MsgUpdateSlotStatusResponse
	11, // 17: contentgrid.registry.v1.Msg.LeaseSlot:output_type -> contentgrid.registry.v1.MsgLeaseSlotResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_contentgrid_registry_v1_tx_proto_init() }
func file_contentgrid_registry_v1_tx_proto_init() {
	if File_contentgrid_registry_v1_tx_proto != nil {
		return
	}
	file_contentgrid_registry_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_registry_v1_tx_proto_rawDesc), len(file_contentgrid_registry_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contentgrid_registry_v1_tx_proto_goTypes,
		DependencyIndexes: file_contentgrid_registry_v1_tx_proto_depIdxs,
		MessageInfos:      file_contentgrid_registry_v1_tx_proto_msgTypes,
	}.Build()
	File_contentgrid_registry_v1_tx_proto = out.File
	file_contentgrid_registry_v1_tx_proto_goTypes = nil
	file_contentgrid_registry_v1_tx_proto_depIdxs = nil
}
