// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: contentgrid/registry/v1/tx.proto

package typespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_RegisterPublisher_FullMethodName        = "/contentgrid.registry.v1.Msg/RegisterPublisher"
	Msg_SubmitVerificationCommit_FullMethodName = "/contentgrid.registry.v1.Msg/SubmitVerificationCommit"
	Msg_RevealVerification_FullMethodName       = "/contentgrid.registry.v1.Msg/RevealVerification"
	Msg_CreateSlot_FullMethodName               = "/contentgrid.registry.v1.Msg/CreateSlot"
	Msg_UpdateSlotStatus_FullMethodName         = "/contentgrid.registry.v1.Msg/UpdateSlotStatus"
	Msg_LeaseSlot_FullMethodName                = "/contentgrid.registry.v1.Msg/LeaseSlot"
	Msg_SubmitDrandBeacon_FullMethodName        = "/contentgrid.registry.v1.Msg/SubmitDrandBeacon"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	RegisterPublisher(ctx context.Context, in *MsgRegisterPublisher, opts ...grpc.CallOption) (*MsgRegisterPublisherResponse, error)
	SubmitVerificationCommit(ctx context.Context, in *MsgSubmitVerificationCommit, opts ...grpc.CallOption) (*MsgSubmitVerificationCommitResponse, error)
	RevealVerification(ctx context.Context, in *MsgRevealVerification, opts ...grpc.CallOption) (*MsgRevealVerificationResponse, error)
	CreateSlot(ctx context.Context, in *MsgCreateSlot, opts ...grpc.CallOption) (*MsgCreateSlotResponse, error)
	UpdateSlotStatus(ctx context.Context, in *MsgUpdateSlotStatus, opts ...grpc.CallOption) (*MsgUpdateSlotStatusResponse, error)
	LeaseSlot(ctx context.Context, in *MsgLeaseSlot, opts ...grpc.CallOption) (*MsgLeaseSlotResponse, error)
	SubmitDrandBeacon(ctx context.Context, in *MsgSubmitDrandBeacon, opts ...grpc.CallOption) (*MsgSubmitDrandBeaconResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterPublisher(ctx context.Context, in *MsgRegisterPublisher, opts ...grpc.CallOption) (*MsgRegisterPublisherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterPublisherResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterPublisher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitVerificationCommit(ctx context.Context, in *MsgSubmitVerificationCommit, opts ...grpc.CallOption) (*MsgSubmitVerificationCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitVerificationCommitResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitVerificationCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealVerification(ctx context.Context, in *MsgRevealVerification, opts ...grpc.CallOption) (*MsgRevealVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevealVerificationResponse)
	err := c.cc.Invoke(ctx, Msg_RevealVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateSlot(ctx context.Context, in *MsgCreateSlot, opts ...grpc.CallOption) (*MsgCreateSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateSlotResponse)
	err := c.cc.Invoke(ctx, Msg_CreateSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateSlotStatus(ctx context.Context, in *MsgUpdateSlotStatus, opts ...grpc.CallOption) (*MsgUpdateSlotStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateSlotStatusResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateSlotStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LeaseSlot(ctx context.Context, in *MsgLeaseSlot, opts ...grpc.CallOption) (*MsgLeaseSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgLeaseSlotResponse)
	err := c.cc.Invoke(ctx, Msg_LeaseSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitDrandBeacon(ctx context.Context, in *MsgSubmitDrandBeacon, opts ...grpc.CallOption) (*MsgSubmitDrandBeaconResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitDrandBeaconResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitDrandBeacon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
type MsgServer interface {
	RegisterPublisher(context.Context, *MsgRegisterPublisher) (*MsgRegisterPublisherResponse, error)
	SubmitVerificationCommit(context.Context, *MsgSubmitVerificationCommit) (*MsgSubmitVerificationCommitResponse, error)
	RevealVerification(context.Context, *MsgRevealVerification) (*MsgRevealVerificationResponse, error)
	CreateSlot(context.Context, *MsgCreateSlot) (*MsgCreateSlotResponse, error)
	UpdateSlotStatus(context.Context, *MsgUpdateSlotStatus) (*MsgUpdateSlotStatusResponse, error)
	LeaseSlot(context.Context, *MsgLeaseSlot) (*MsgLeaseSlotResponse, error)
	SubmitDrandBeacon(context.Context, *MsgSubmitDrandBeacon) (*MsgSubmitDrandBeaconResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) RegisterPublisher(context.Context, *MsgRegisterPublisher) (*MsgRegisterPublisherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPublisher not implemented")
}
func (UnimplementedMsgServer) SubmitVerificationCommit(context.Context, *MsgSubmitVerificationCommit) (*MsgSubmitVerificationCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitVerificationCommit not implemented")
}
func (UnimplementedMsgServer) RevealVerification(context.Context, *MsgRevealVerification) (*MsgRevealVerificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevealVerification not implemented")
}
func (UnimplementedMsgServer) CreateSlot(context.Context, *MsgCreateSlot) (*MsgCreateSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSlot not implemented")
}
func (UnimplementedMsgServer) UpdateSlotStatus(context.Context, *MsgUpdateSlotStatus) (*MsgUpdateSlotStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSlotStatus not implemented")
}
func (UnimplementedMsgServer) LeaseSlot(context.Context, *MsgLeaseSlot) (*MsgLeaseSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseSlot not implemented")
}
func (UnimplementedMsgServer) SubmitDrandBeacon(context.Context, *MsgSubmitDrandBeacon) (*MsgSubmitDrandBeaconResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDrandBeacon not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_RegisterPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterPublisher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterPublisher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterPublisher(ctx, req.(*MsgRegisterPublisher))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitVerificationCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitVerificationCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitVerificationCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitVerificationCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitVerificationCommit(ctx, req.(*MsgSubmitVerificationCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealVerification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevealVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealVerification(ctx, req.(*MsgRevealVerification))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSlot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSlot(ctx, req.(*MsgCreateSlot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateSlotStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateSlotStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateSlotStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateSlotStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateSlotStatus(ctx, req.(*MsgUpdateSlotStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LeaseSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLeaseSlot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LeaseSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_LeaseSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LeaseSlot(ctx, req.(*MsgLeaseSlot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitDrandBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitDrandBeacon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitDrandBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitDrandBeacon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitDrandBeacon(ctx, req.(*MsgSubmitDrandBeacon))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contentgrid.registry.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPublisher",
			Handler:    _Msg_RegisterPublisher_Handler,
		},
		{
			MethodName: "SubmitVerificationCommit",
			Handler:    _Msg_SubmitVerificationCommit_Handler,
		},
		{
			MethodName: "RevealVerification",
			Handler:    _Msg_RevealVerification_Handler,
		},
		{
			MethodName: "CreateSlot",
			Handler:    _Msg_CreateSlot_Handler,
		},
		{
			MethodName: "UpdateSlotStatus",
			Handler:    _Msg_UpdateSlotStatus_Handler,
		},
		{
			MethodName: "LeaseSlot",
			Handler:    _Msg_LeaseSlot_Handler,
		},
		{
			MethodName: "SubmitDrandBeacon",
			Handler:    _Msg_SubmitDrandBeacon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contentgrid/registry/v1/tx.proto",
}
