// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentgrid/registry/v1/types.proto

package typespb

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebsiteStatus int32

const (
	WebsiteStatus_WEBSITE_STATUS_UNSPECIFIED WebsiteStatus = 0
	WebsiteStatus_WEBSITE_STATUS_PENDING     WebsiteStatus = 1
	WebsiteStatus_WEBSITE_STATUS_VERIFIED    WebsiteStatus = 2
	WebsiteStatus_WEBSITE_STATUS_REVOKED     WebsiteStatus = 3
)

// Enum value maps for WebsiteStatus.
var (
	WebsiteStatus_name = map[int32]string{
		0: "WEBSITE_STATUS_UNSPECIFIED",
		1: "WEBSITE_STATUS_PENDING",
		2: "WEBSITE_STATUS_VERIFIED",
		3: "WEBSITE_STATUS_REVOKED",
	}
	WebsiteStatus_value = map[string]int32{
		"WEBSITE_STATUS_UNSPECIFIED": 0,
		"WEBSITE_STATUS_PENDING":     1,
		"WEBSITE_STATUS_VERIFIED":    2,
		"WEBSITE_STATUS_REVOKED":     3,
	}
)

func (x WebsiteStatus) Enum() *WebsiteStatus {
	p := new(WebsiteStatus)
	*p = x
	return p
}

func (x WebsiteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsiteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contentgrid_registry_v1_types_proto_enumTypes[0].Descriptor()
}

func (WebsiteStatus) Type() protoreflect.EnumType {
	return &file_contentgrid_registry_v1_types_proto_enumTypes[0]
}

func (x WebsiteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsiteStatus.Descriptor instead.
func (WebsiteStatus) EnumDescriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{0}
}

type SlotStatus int32

const (
	SlotStatus_SLOT_STATUS_UNSPECIFIED SlotStatus = 0
	SlotStatus_SLOT_STATUS_LISTED      SlotStatus = 1
	SlotStatus_SLOT_STATUS_PAUSED      SlotStatus = 2
	SlotStatus_SLOT_STATUS_UNLISTED    SlotStatus = 3
)

// Enum value maps for SlotStatus.
var (
	SlotStatus_name = map[int32]string{
		0: "SLOT_STATUS_UNSPECIFIED",
		1: "SLOT_STATUS_LISTED",
		2: "SLOT_STATUS_PAUSED",
		3: "SLOT_STATUS_UNLISTED",
	}
	SlotStatus_value = map[string]int32{
		"SLOT_STATUS_UNSPECIFIED": 0,
		"SLOT_STATUS_LISTED":      1,
		"SLOT_STATUS_PAUSED":      2,
		"SLOT_STATUS_UNLISTED":    3,
	}
)

func (x SlotStatus) Enum() *SlotStatus {
	p := new(SlotStatus)
	*p = x
	return p
}

func (x SlotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contentgrid_registry_v1_types_proto_enumTypes[1].Descriptor()
}

func (SlotStatus) Type() protoreflect.EnumType {
	return &file_contentgrid_registry_v1_types_proto_enumTypes[1]
}

func (x SlotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotStatus.Descriptor instead.
func (SlotStatus) EnumDescriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{1}
}

type LeaseStatus int32

const (
	LeaseStatus_LEASE_STATUS_UNSPECIFIED LeaseStatus = 0
	LeaseStatus_LEASE_STATUS_ACTIVE      LeaseStatus = 1
	LeaseStatus_LEASE_STATUS_COMPLETED   LeaseStatus = 2
	LeaseStatus_LEASE_STATUS_VIOLATED    LeaseStatus = 3
	LeaseStatus_LEASE_STATUS_REFUNDED    LeaseStatus = 4
)

// Enum value maps for LeaseStatus.
var (
	LeaseStatus_name = map[int32]string{
		0: "LEASE_STATUS_UNSPECIFIED",
		1: "LEASE_STATUS_ACTIVE",
		2: "LEASE_STATUS_COMPLETED",
		3: "LEASE_STATUS_VIOLATED",
		4: "LEASE_STATUS_REFUNDED",
	}
	LeaseStatus_value = map[string]int32{
		"LEASE_STATUS_UNSPECIFIED": 0,
		"LEASE_STATUS_ACTIVE":      1,
		"LEASE_STATUS_COMPLETED":   2,
		"LEASE_STATUS_VIOLATED":    3,
		"LEASE_STATUS_REFUNDED":    4,
	}
)

func (x LeaseStatus) Enum() *LeaseStatus {
	p := new(LeaseStatus)
	*p = x
	return p
}

func (x LeaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contentgrid_registry_v1_types_proto_enumTypes[2].Descriptor()
}

func (LeaseStatus) Type() protoreflect.EnumType {
	return &file_contentgrid_registry_v1_types_proto_enumTypes[2]
}

func (x LeaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseStatus.Descriptor instead.
func (LeaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{2}
}

type Website struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Domain             string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Owner              string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Status             WebsiteStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=contentgrid.registry.v1.WebsiteStatus" json:"status,omitempty"`
	MetadataUri        string                 `protobuf:"bytes,4,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	Proof              string                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	RegisteredAtHeight int64                  `protobuf:"varint,6,opt,name=registered_at_height,json=registeredAtHeight,proto3" json:"registered_at_height,omitempty"`
	Verifier           string                 `protobuf:"bytes,7,opt,name=verifier,proto3" json:"verifier,omitempty"`
	// Optional referrer address associated with the initial registration.
	Referrer string `protobuf:"bytes,8,opt,name=referrer,proto3" json:"referrer,omitempty"`
	// Cooldown enforcement after failed verification.
	CooldownUntilUnix int64 `protobuf:"varint,9,opt,name=cooldown_until_unix,json=cooldownUntilUnix,proto3" json:"cooldown_until_unix,omitempty"`
	CooldownCount     int32 `protobuf:"varint,10,opt,name=cooldown_count,json=cooldownCount,proto3" json:"cooldown_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Website) Reset() {
	*x = Website{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Website) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Website) ProtoMessage() {}

func (x *Website) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Website.ProtoReflect.Descriptor instead.
func (*Website) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Website) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Website) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Website) GetStatus() WebsiteStatus {
	if x != nil {
		return x.Status
	}
	return WebsiteStatus_WEBSITE_STATUS_UNSPECIFIED
}

func (x *Website) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *Website) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *Website) GetRegisteredAtHeight() int64 {
	if x != nil {
		return x.RegisteredAtHeight
	}
	return 0
}

func (x *Website) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *Website) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *Website) GetCooldownUntilUnix() int64 {
	if x != nil {
		return x.CooldownUntilUnix
	}
	return 0
}

func (x *Website) GetCooldownCount() int32 {
	if x != nil {
		return x.CooldownCount
	}
	return 0
}

type PublisherVerificationAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoundStartUnix  int64                  `protobuf:"varint,1,opt,name=round_start_unix,json=roundStartUnix,proto3" json:"round_start_unix,omitempty"`
	Domain          string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	StartAtUnix     int64                  `protobuf:"varint,3,opt,name=start_at_unix,json=startAtUnix,proto3" json:"start_at_unix,omitempty"`
	DeadlineUnix    int64                  `protobuf:"varint,4,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	Verifiers       []string               `protobuf:"bytes,5,rep,name=verifiers,proto3" json:"verifiers,omitempty"`
	Finalized       bool                   `protobuf:"varint,6,opt,name=finalized,proto3" json:"finalized,omitempty"`
	FinalizedAtUnix int64                  `protobuf:"varint,7,opt,name=finalized_at_unix,json=finalizedAtUnix,proto3" json:"finalized_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublisherVerificationAssignment) Reset() {
	*x = PublisherVerificationAssignment{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherVerificationAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherVerificationAssignment) ProtoMessage() {}

func (x *PublisherVerificationAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherVerificationAssignment.ProtoReflect.Descriptor instead.
func (*PublisherVerificationAssignment) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *PublisherVerificationAssignment) GetRoundStartUnix() int64 {
	if x != nil {
		return x.RoundStartUnix
	}
	return 0
}

func (x *PublisherVerificationAssignment) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PublisherVerificationAssignment) GetStartAtUnix() int64 {
	if x != nil {
		return x.StartAtUnix
	}
	return 0
}

func (x *PublisherVerificationAssignment) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *PublisherVerificationAssignment) GetVerifiers() []string {
	if x != nil {
		return x.Verifiers
	}
	return nil
}

func (x *PublisherVerificationAssignment) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *PublisherVerificationAssignment) GetFinalizedAtUnix() int64 {
	if x != nil {
		return x.FinalizedAtUnix
	}
	return 0
}

type PublisherVerificationSubmission struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoundStartUnix  int64                  `protobuf:"varint,1,opt,name=round_start_unix,json=roundStartUnix,proto3" json:"round_start_unix,omitempty"`
	Domain          string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Verifier        string                 `protobuf:"bytes,3,opt,name=verifier,proto3" json:"verifier,omitempty"`
	Passed          bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	ObservedAtUnix  int64                  `protobuf:"varint,5,opt,name=observed_at_unix,json=observedAtUnix,proto3" json:"observed_at_unix,omitempty"`
	LatencyMs       int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	SubmittedAtUnix int64                  `protobuf:"varint,7,opt,name=submitted_at_unix,json=submittedAtUnix,proto3" json:"submitted_at_unix,omitempty"`
	// Similar-site verification metrics (domain-only, no paths).
	ObservedSimilarDomains int32  `protobuf:"varint,8,opt,name=observed_similar_domains,json=observedSimilarDomains,proto3" json:"observed_similar_domains,omitempty"`
	MatchedSimilarDomains  int32  `protobuf:"varint,9,opt,name=matched_similar_domains,json=matchedSimilarDomains,proto3" json:"matched_similar_domains,omitempty"`
	ExpectedSimilarDomains int32  `protobuf:"varint,10,opt,name=expected_similar_domains,json=expectedSimilarDomains,proto3" json:"expected_similar_domains,omitempty"`
	ExpectedSetHash        string `protobuf:"bytes,11,opt,name=expected_set_hash,json=expectedSetHash,proto3" json:"expected_set_hash,omitempty"`
	ObservedSetHash        string `protobuf:"bytes,12,opt,name=observed_set_hash,json=observedSetHash,proto3" json:"observed_set_hash,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublisherVerificationSubmission) Reset() {
	*x = PublisherVerificationSubmission{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherVerificationSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherVerificationSubmission) ProtoMessage() {}

func (x *PublisherVerificationSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherVerificationSubmission.ProtoReflect.Descriptor instead.
func (*PublisherVerificationSubmission) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *PublisherVerificationSubmission) GetRoundStartUnix() int64 {
	if x != nil {
		return x.RoundStartUnix
	}
	return 0
}

func (x *PublisherVerificationSubmission) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PublisherVerificationSubmission) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *PublisherVerificationSubmission) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *PublisherVerificationSubmission) GetObservedAtUnix() int64 {
	if x != nil {
		return x.ObservedAtUnix
	}
	return 0
}

func (x *PublisherVerificationSubmission) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PublisherVerificationSubmission) GetSubmittedAtUnix() int64 {
	if x != nil {
		return x.SubmittedAtUnix
	}
	return 0
}

func (x *PublisherVerificationSubmission) GetObservedSimilarDomains() int32 {
	if x != nil {
		return x.ObservedSimilarDomains
	}
	return 0
}

func (x *PublisherVerificationSubmission) GetMatchedSimilarDomains() int32 {
	if x != nil {
		return x.MatchedSimilarDomains
	}
	return 0
}

func (x *PublisherVerificationSubmission) GetExpectedSimilarDomains() int32 {
	if x != nil {
		return x.ExpectedSimilarDomains
	}
	return 0
}

func (x *PublisherVerificationSubmission) GetExpectedSetHash() string {
	if x != nil {
		return x.ExpectedSetHash
	}
	return ""
}

func (x *PublisherVerificationSubmission) GetObservedSetHash() string {
	if x != nil {
		return x.ObservedSetHash
	}
	return ""
}

type VerificationRoundMeta struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RoundStartUnix            int64                  `protobuf:"varint,1,opt,name=round_start_unix,json=roundStartUnix,proto3" json:"round_start_unix,omitempty"`
	SeedHex                   string                 `protobuf:"bytes,2,opt,name=seed_hex,json=seedHex,proto3" json:"seed_hex,omitempty"`
	RoundIntervalSeconds      int64                  `protobuf:"varint,3,opt,name=round_interval_seconds,json=roundIntervalSeconds,proto3" json:"round_interval_seconds,omitempty"`
	AssignmentDelayMaxSeconds int64                  `protobuf:"varint,4,opt,name=assignment_delay_max_seconds,json=assignmentDelayMaxSeconds,proto3" json:"assignment_delay_max_seconds,omitempty"`
	CreatedAtUnix             int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	AnchorHeight              int64                  `protobuf:"varint,6,opt,name=anchor_height,json=anchorHeight,proto3" json:"anchor_height,omitempty"`
	AnchorHashHex             string                 `protobuf:"bytes,7,opt,name=anchor_hash_hex,json=anchorHashHex,proto3" json:"anchor_hash_hex,omitempty"`
	VerifierSetHash           string                 `protobuf:"bytes,8,opt,name=verifier_set_hash,json=verifierSetHash,proto3" json:"verifier_set_hash,omitempty"`
	VerifierSetSize           int32                  `protobuf:"varint,9,opt,name=verifier_set_size,json=verifierSetSize,proto3" json:"verifier_set_size,omitempty"`
	DrandRound                uint64                 `protobuf:"varint,10,opt,name=drand_round,json=drandRound,proto3" json:"drand_round,omitempty"`
	DrandRandomnessHex        string                 `protobuf:"bytes,11,opt,name=drand_randomness_hex,json=drandRandomnessHex,proto3" json:"drand_randomness_hex,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *VerificationRoundMeta) Reset() {
	*x = VerificationRoundMeta{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRoundMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRoundMeta) ProtoMessage() {}

func (x *VerificationRoundMeta) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRoundMeta.ProtoReflect.Descriptor instead.
func (*VerificationRoundMeta) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationRoundMeta) GetRoundStartUnix() int64 {
	if x != nil {
		return x.RoundStartUnix
	}
	return 0
}

func (x *VerificationRoundMeta) GetSeedHex() string {
	if x != nil {
		return x.SeedHex
	}
	return ""
}

func (x *VerificationRoundMeta) GetRoundIntervalSeconds() int64 {
	if x != nil {
		return x.RoundIntervalSeconds
	}
	return 0
}

func (x *VerificationRoundMeta) GetAssignmentDelayMaxSeconds() int64 {
	if x != nil {
		return x.AssignmentDelayMaxSeconds
	}
	return 0
}

func (x *VerificationRoundMeta) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *VerificationRoundMeta) GetAnchorHeight() int64 {
	if x != nil {
		return x.AnchorHeight
	}
	return 0
}

func (x *VerificationRoundMeta) GetAnchorHashHex() string {
	if x != nil {
		return x.AnchorHashHex
	}
	return ""
}

func (x *VerificationRoundMeta) GetVerifierSetHash() string {
	if x != nil {
		return x.VerifierSetHash
	}
	return ""
}

func (x *VerificationRoundMeta) GetVerifierSetSize() int32 {
	if x != nil {
		return x.VerifierSetSize
	}
	return 0
}

func (x *VerificationRoundMeta) GetDrandRound() uint64 {
	if x != nil {
		return x.DrandRound
	}
	return 0
}

func (x *VerificationRoundMeta) GetDrandRandomnessHex() string {
	if x != nil {
		return x.DrandRandomnessHex
	}
	return ""
}

type DrandBeacon struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Round           uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	RandomnessHex   string                 `protobuf:"bytes,2,opt,name=randomness_hex,json=randomnessHex,proto3" json:"randomness_hex,omitempty"`
	SignatureHex    string                 `protobuf:"bytes,3,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	SubmittedAtUnix int64                  `protobuf:"varint,4,opt,name=submitted_at_unix,json=submittedAtUnix,proto3" json:"submitted_at_unix,omitempty"`
	Submitter       string                 `protobuf:"bytes,5,opt,name=submitter,proto3" json:"submitter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DrandBeacon) Reset() {
	*x = DrandBeacon{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrandBeacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrandBeacon) ProtoMessage() {}

func (x *DrandBeacon) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrandBeacon.ProtoReflect.Descriptor instead.
func (*DrandBeacon) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *DrandBeacon) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *DrandBeacon) GetRandomnessHex() string {
	if x != nil {
		return x.RandomnessHex
	}
	return ""
}

func (x *DrandBeacon) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

func (x *DrandBeacon) GetSubmittedAtUnix() int64 {
	if x != nil {
		return x.SubmittedAtUnix
	}
	return 0
}

func (x *DrandBeacon) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

type VerifierAssignment struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Assignment    *PublisherVerificationAssignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Submission    *PublisherVerificationSubmission `protobuf:"bytes,2,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifierAssignment) Reset() {
	*x = VerifierAssignment{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifierAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifierAssignment) ProtoMessage() {}

func (x *VerifierAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifierAssignment.ProtoReflect.Descriptor instead.
func (*VerifierAssignment) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *VerifierAssignment) GetAssignment() *PublisherVerificationAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *VerifierAssignment) GetSubmission() *PublisherVerificationSubmission {
	if x != nil {
		return x.Submission
	}
	return nil
}

// Latest similar-site settlement for a publisher (domain-only, no paths).
type PublisherSimilarStats struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Domain                 string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	RoundStartUnix         int64                  `protobuf:"varint,2,opt,name=round_start_unix,json=roundStartUnix,proto3" json:"round_start_unix,omitempty"`
	VerifiedSimilarDomains int32                  `protobuf:"varint,3,opt,name=verified_similar_domains,json=verifiedSimilarDomains,proto3" json:"verified_similar_domains,omitempty"`
	ExpectedSetHash        string                 `protobuf:"bytes,4,opt,name=expected_set_hash,json=expectedSetHash,proto3" json:"expected_set_hash,omitempty"`
	VerifiedAtUnix         int64                  `protobuf:"varint,5,opt,name=verified_at_unix,json=verifiedAtUnix,proto3" json:"verified_at_unix,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublisherSimilarStats) Reset() {
	*x = PublisherSimilarStats{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherSimilarStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherSimilarStats) ProtoMessage() {}

func (x *PublisherSimilarStats) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherSimilarStats.ProtoReflect.Descriptor instead.
func (*PublisherSimilarStats) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *PublisherSimilarStats) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PublisherSimilarStats) GetRoundStartUnix() int64 {
	if x != nil {
		return x.RoundStartUnix
	}
	return 0
}

func (x *PublisherSimilarStats) GetVerifiedSimilarDomains() int32 {
	if x != nil {
		return x.VerifiedSimilarDomains
	}
	return 0
}

func (x *PublisherSimilarStats) GetExpectedSetHash() string {
	if x != nil {
		return x.ExpectedSetHash
	}
	return ""
}

func (x *PublisherSimilarStats) GetVerifiedAtUnix() int64 {
	if x != nil {
		return x.VerifiedAtUnix
	}
	return 0
}

type Slot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Publisher          string                 `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Domain             string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Label              string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Summary            string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Category           string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Placement          string                 `protobuf:"bytes,7,opt,name=placement,proto3" json:"placement,omitempty"`
	Size               string                 `protobuf:"bytes,8,opt,name=size,proto3" json:"size,omitempty"`
	RateDenom          string                 `protobuf:"bytes,9,opt,name=rate_denom,json=rateDenom,proto3" json:"rate_denom,omitempty"`
	RateAmount         string                 `protobuf:"bytes,10,opt,name=rate_amount,json=rateAmount,proto3" json:"rate_amount,omitempty"`
	UnitSeconds        int64                  `protobuf:"varint,11,opt,name=unit_seconds,json=unitSeconds,proto3" json:"unit_seconds,omitempty"`
	MinDurationSeconds int64                  `protobuf:"varint,12,opt,name=min_duration_seconds,json=minDurationSeconds,proto3" json:"min_duration_seconds,omitempty"`
	MaxDurationSeconds int64                  `protobuf:"varint,13,opt,name=max_duration_seconds,json=maxDurationSeconds,proto3" json:"max_duration_seconds,omitempty"`
	Status             SlotStatus             `protobuf:"varint,14,opt,name=status,proto3,enum=contentgrid.registry.v1.SlotStatus" json:"status,omitempty"`
	CreatedAtUnix      int64                  `protobuf:"varint,15,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix      int64                  `protobuf:"varint,16,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Tags               []string               `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *Slot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Slot) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Slot) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Slot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Slot) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Slot) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Slot) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

func (x *Slot) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Slot) GetRateDenom() string {
	if x != nil {
		return x.RateDenom
	}
	return ""
}

func (x *Slot) GetRateAmount() string {
	if x != nil {
		return x.RateAmount
	}
	return ""
}

func (x *Slot) GetUnitSeconds() int64 {
	if x != nil {
		return x.UnitSeconds
	}
	return 0
}

func (x *Slot) GetMinDurationSeconds() int64 {
	if x != nil {
		return x.MinDurationSeconds
	}
	return 0
}

func (x *Slot) GetMaxDurationSeconds() int64 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

func (x *Slot) GetStatus() SlotStatus {
	if x != nil {
		return x.Status
	}
	return SlotStatus_SLOT_STATUS_UNSPECIFIED
}

func (x *Slot) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Slot) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *Slot) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SlotLease struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SlotId          string                 `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Publisher       string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Lessee          string                 `protobuf:"bytes,4,opt,name=lessee,proto3" json:"lessee,omitempty"`
	TargetUrl       string                 `protobuf:"bytes,5,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	StartsAtUnix    int64                  `protobuf:"varint,6,opt,name=starts_at_unix,json=startsAtUnix,proto3" json:"starts_at_unix,omitempty"`
	EndsAtUnix      int64                  `protobuf:"varint,7,opt,name=ends_at_unix,json=endsAtUnix,proto3" json:"ends_at_unix,omitempty"`
	RateDenom       string                 `protobuf:"bytes,8,opt,name=rate_denom,json=rateDenom,proto3" json:"rate_denom,omitempty"`
	RateAmount      string                 `protobuf:"bytes,9,opt,name=rate_amount,json=rateAmount,proto3" json:"rate_amount,omitempty"`
	UnitSeconds     int64                  `protobuf:"varint,10,opt,name=unit_seconds,json=unitSeconds,proto3" json:"unit_seconds,omitempty"`
	EscrowTotal     string                 `protobuf:"bytes,11,opt,name=escrow_total,json=escrowTotal,proto3" json:"escrow_total,omitempty"`
	EscrowRemaining string                 `protobuf:"bytes,12,opt,name=escrow_remaining,json=escrowRemaining,proto3" json:"escrow_remaining,omitempty"`
	PaidOut         string                 `protobuf:"bytes,13,opt,name=paid_out,json=paidOut,proto3" json:"paid_out,omitempty"`
	Status          LeaseStatus            `protobuf:"varint,14,opt,name=status,proto3,enum=contentgrid.registry.v1.LeaseStatus" json:"status,omitempty"`
	CreatedAtUnix   int64                  `protobuf:"varint,15,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix   int64                  `protobuf:"varint,16,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	PaidThroughUnix int64                  `protobuf:"varint,17,opt,name=paid_through_unix,json=paidThroughUnix,proto3" json:"paid_through_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SlotLease) Reset() {
	*x = SlotLease{}
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotLease) ProtoMessage() {}

func (x *SlotLease) ProtoReflect() protoreflect.Message {
	mi := &file_contentgrid_registry_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotLease.ProtoReflect.Descriptor instead.
func (*SlotLease) Descriptor() ([]byte, []int) {
	return file_contentgrid_registry_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *SlotLease) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SlotLease) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *SlotLease) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *SlotLease) GetLessee() string {
	if x != nil {
		return x.Lessee
	}
	return ""
}

func (x *SlotLease) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *SlotLease) GetStartsAtUnix() int64 {
	if x != nil {
		return x.StartsAtUnix
	}
	return 0
}

func (x *SlotLease) GetEndsAtUnix() int64 {
	if x != nil {
		return x.EndsAtUnix
	}
	return 0
}

func (x *SlotLease) GetRateDenom() string {
	if x != nil {
		return x.RateDenom
	}
	return ""
}

func (x *SlotLease) GetRateAmount() string {
	if x != nil {
		return x.RateAmount
	}
	return ""
}

func (x *SlotLease) GetUnitSeconds() int64 {
	if x != nil {
		return x.UnitSeconds
	}
	return 0
}

func (x *SlotLease) GetEscrowTotal() string {
	if x != nil {
		return x.EscrowTotal
	}
	return ""
}

func (x *SlotLease) GetEscrowRemaining() string {
	if x != nil {
		return x.EscrowRemaining
	}
	return ""
}

func (x *SlotLease) GetPaidOut() string {
	if x != nil {
		return x.PaidOut
	}
	return ""
}

func (x *SlotLease) GetStatus() LeaseStatus {
	if x != nil {
		return x.Status
	}
	return LeaseStatus_LEASE_STATUS_UNSPECIFIED
}

func (x *SlotLease) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *SlotLease) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *SlotLease) GetPaidThroughUnix() int64 {
	if x != nil {
		return x.PaidThroughUnix
	}
	return 0
}

var File_contentgrid_registry_v1_types_proto protoreflect.FileDescriptor

const file_contentgrid_registry_v1_types_proto_rawDesc = "" +
	"\n" +
	"#contentgrid/registry/v1/types.proto\x12\x17contentgrid.registry.v1\x1a\x14gogoproto/gogo.proto\"\xf1\x02\n" +
	"\aWebsite\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.contentgrid.registry.v1.WebsiteStatusR\x06status\x12!\n" +
	"\fmetadata_uri\x18\x04 \x01(\tR\vmetadataUri\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\tR\x05proof\x120\n" +
	"\x14registered_at_height\x18\x06 \x01(\x03R\x12registeredAtHeight\x12\x1a\n" +
	"\bverifier\x18\a \x01(\tR\bverifier\x12\x1a\n" +
	"\breferrer\x18\b \x01(\tR\breferrer\x12.\n" +
	"\x13cooldown_until_unix\x18\t \x01(\x03R\x11cooldownUntilUnix\x12%\n" +
	"\x0ecooldown_count\x18\n" +
	" \x01(\x05R\rcooldownCount\"\x94\x02\n" +
	"\x1fPublisherVerificationAssignment\x12(\n" +
	"\x10round_start_unix\x18\x01 \x01(\x03R\x0eroundStartUnix\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\"\n" +
	"\rstart_at_unix\x18\x03 \x01(\x03R\vstartAtUnix\x12#\n" +
	"\rdeadline_unix\x18\x04 \x01(\x03R\fdeadlineUnix\x12\x1c\n" +
	"\tverifiers\x18\x05 \x03(\tR\tverifiers\x12\x1c\n" +
	"\tfinalized\x18\x06 \x01(\bR\tfinalized\x12*\n" +
	"\x11finalized_at_unix\x18\a \x01(\x03R\x0ffinalizedAtUnix\"\x90\x04\n" +
	"\x1fPublisherVerificationSubmission\x12(\n" +
	"\x10round_start_unix\x18\x01 \x01(\x03R\x0eroundStartUnix\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1a\n" +
	"\bverifier\x18\x03 \x01(\tR\bverifier\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12(\n" +
	"\x10observed_at_unix\x18\x05 \x01(\x03R\x0eobservedAtUnix\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12*\n" +
	"\x11submitted_at_unix\x18\a \x01(\x03R\x0fsubmittedAtUnix\x128\n" +
	"\x18observed_similar_domains\x18\b \x01(\x05R\x16observedSimilarDomains\x126\n" +
	"\x17matched_similar_domains\x18\t \x01(\x05R\x15matchedSimilarDomains\x128\n" +
	"\x18expected_similar_domains\x18\n" +
	" \x01(\x05R\x16expectedSimilarDomains\x12*\n" +
	"\x11expected_set_hash\x18\v \x01(\tR\x0fexpectedSetHash\x12*\n" +
	"\x11observed_set_hash\x18\f \x01(\tR\x0fobservedSetHash\"\xf3\x03\n" +
	"\x15VerificationRoundMeta\x12(\n" +
	"\x10round_start_unix\x18\x01 \x01(\x03R\x0eroundStartUnix\x12\x19\n" +
	"\bseed_hex\x18\x02 \x01(\tR\aseedHex\x124\n" +
	"\x16round_interval_seconds\x18\x03 \x01(\x03R\x14roundIntervalSeconds\x12?\n" +
	"\x1cassignment_delay_max_seconds\x18\x04 \x01(\x03R\x19assignmentDelayMaxSeconds\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\x12#\n" +
	"\ranchor_height\x18\x06 \x01(\x03R\fanchorHeight\x12&\n" +
	"\x0fanchor_hash_hex\x18\a \x01(\tR\ranchorHashHex\x12*\n" +
	"\x11verifier_set_hash\x18\b \x01(\tR\x0fverifierSetHash\x12*\n" +
	"\x11verifier_set_size\x18\t \x01(\x05R\x0fverifierSetSize\x12\x1f\n" +
	"\vdrand_round\x18\n" +
	" \x01(\x04R\n" +
	"drandRound\x120\n" +
	"\x14drand_randomness_hex\x18\v \x01(\tR\x12drandRandomnessHex\"\xb9\x01\n" +
	"\vDrandBeacon\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12%\n" +
	"\x0erandomness_hex\x18\x02 \x01(\tR\rrandomnessHex\x12#\n" +
	"\rsignature_hex\x18\x03 \x01(\tR\fsignatureHex\x12*\n" +
	"\x11submitted_at_unix\x18\x04 \x01(\x03R\x0fsubmittedAtUnix\x12\x1c\n" +
	"\tsubmitter\x18\x05 \x01(\tR\tsubmitter\"\xc8\x01\n" +
	"\x12VerifierAssignment\x12X\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v28.contentgrid.registry.v1.PublisherVerificationAssignmentR\n" +
	"assignment\x12X\n" +
	"\n" +
	"submission\x18\x02 \x01(\v28.contentgrid.registry.v1.PublisherVerificationSubmissionR\n" +
	"submission\"\xe9\x01\n" +
	"\x15PublisherSimilarStats\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12(\n" +
	"\x10round_start_unix\x18\x02 \x01(\x03R\x0eroundStartUnix\x128\n" +
	"\x18verified_similar_domains\x18\x03 \x01(\x05R\x16verifiedSimilarDomains\x12*\n" +
	"\x11expected_set_hash\x18\x04 \x01(\tR\x0fexpectedSetHash\x12(\n" +
	"\x10verified_at_unix\x18\x05 \x01(\x03R\x0everifiedAtUnix\"\xb2\x04\n" +
	"\x04Slot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tpublisher\x18\x02 \x01(\tR\tpublisher\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1c\n" +
	"\tplacement\x18\a \x01(\tR\tplacement\x12\x12\n" +
	"\x04size\x18\b \x01(\tR\x04size\x12\x1d\n" +
	"\n" +
	"rate_denom\x18\t \x01(\tR\trateDenom\x12\x1f\n" +
	"\vrate_amount\x18\n" +
	" \x01(\tR\n" +
	"rateAmount\x12!\n" +
	"\funit_seconds\x18\v \x01(\x03R\vunitSeconds\x120\n" +
	"\x14min_duration_seconds\x18\f \x01(\x03R\x12minDurationSeconds\x120\n" +
	"\x14max_duration_seconds\x18\r \x01(\x03R\x12maxDurationSeconds\x12;\n" +
	"\x06status\x18\x0e \x01(\x0e2#.contentgrid.registry.v1.SlotStatusR\x06status\x12&\n" +
	"\x0fcreated_at_unix\x18\x0f \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x10 \x01(\x03R\rupdatedAtUnix\x12\x12\n" +
	"\x04tags\x18\x11 \x03(\tR\x04tags\"\xd7\x04\n" +
	"\tSlotLease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\tR\x06slotId\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\x12\x16\n" +
	"\x06lessee\x18\x04 \x01(\tR\x06lessee\x12\x1d\n" +
	"\n" +
	"target_url\x18\x05 \x01(\tR\ttargetUrl\x12$\n" +
	"\x0estarts_at_unix\x18\x06 \x01(\x03R\fstartsAtUnix\x12 \n" +
	"\fends_at_unix\x18\a \x01(\x03R\n" +
	"endsAtUnix\x12\x1d\n" +
	"\n" +
	"rate_denom\x18\b \x01(\tR\trateDenom\x12\x1f\n" +
	"\vrate_amount\x18\t \x01(\tR\n" +
	"rateAmount\x12!\n" +
	"\funit_seconds\x18\n" +
	" \x01(\x03R\vunitSeconds\x12!\n" +
	"\fescrow_total\x18\v \x01(\tR\vescrowTotal\x12)\n" +
	"\x10escrow_remaining\x18\f \x01(\tR\x0fescrowRemaining\x12\x19\n" +
	"\bpaid_out\x18\r \x01(\tR\apaidOut\x12<\n" +
	"\x06status\x18\x0e \x01(\x0e2$.contentgrid.registry.v1.LeaseStatusR\x06status\x12&\n" +
	"\x0fcreated_at_unix\x18\x0f \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x10 \x01(\x03R\rupdatedAtUnix\x12*\n" +
	"\x11paid_through_unix\x18\x11 \x01(\x03R\x0fpaidThroughUnix*\x84\x01\n" +
	"\rWebsiteStatus\x12\x1e\n" +
	"\x1aWEBSITE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WEBSITE_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17WEBSITE_STATUS_VERIFIED\x10\x02\x12\x1a\n" +
	"\x16WEBSITE_STATUS_REVOKED\x10\x03*s\n" +
	"\n" +
	"SlotStatus\x12\x1b\n" +
	"\x17SLOT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SLOT_STATUS_LISTED\x10\x01\x12\x16\n" +
	"\x12SLOT_STATUS_PAUSED\x10\x02\x12\x18\n" +
	"\x14SLOT_STATUS_UNLISTED\x10\x03*\x96\x01\n" +
	"\vLeaseStatus\x12\x1c\n" +
	"\x18LEASE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13LEASE_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16LEASE_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15LEASE_STATUS_VIOLATED\x10\x03\x12\x19\n" +
	"\x15LEASE_STATUS_REFUNDED\x10\x04B'Z%content-grid-chain/x/registry/typespbb\x06proto3"

var (
	file_contentgrid_registry_v1_types_proto_rawDescOnce sync.Once
	file_contentgrid_registry_v1_types_proto_rawDescData []byte
)

func file_contentgrid_registry_v1_types_proto_rawDescGZIP() []byte {
	file_contentgrid_registry_v1_types_proto_rawDescOnce.Do(func() {
		file_contentgrid_registry_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentgrid_registry_v1_types_proto_rawDesc), len(file_contentgrid_registry_v1_types_proto_rawDesc)))
	})
	return file_contentgrid_registry_v1_types_proto_rawDescData
}

var file_contentgrid_registry_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_contentgrid_registry_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_contentgrid_registry_v1_types_proto_goTypes = []any{
	(WebsiteStatus)(0),                      // 0: contentgrid.registry.v1.WebsiteStatus
	(SlotStatus)(0),                         // 1: contentgrid.registry.v1.SlotStatus
	(LeaseStatus)(0),                        // 2: contentgrid.registry.v1.LeaseStatus
	(*Website)(nil),                         // 3: contentgrid.registry.v1.Website
	(*PublisherVerificationAssignment)(nil), // 4: contentgrid.registry.v1.PublisherVerificationAssignment
	(*PublisherVerificationSubmission)(nil), // 5: contentgrid.registry.v1.PublisherVerificationSubmission
	(*VerificationRoundMeta)(nil),           // 6: contentgrid.registry.v1.VerificationRoundMeta
	(*DrandBeacon)(nil),                     // 7: contentgrid.registry.v1.DrandBeacon
	(*VerifierAssignment)(nil),              // 8: contentgrid.registry.v1.VerifierAssignment
	(*PublisherSimilarStats)(nil),           // 9: contentgrid.registry.v1.PublisherSimilarStats
	(*Slot)(nil),                            // 10: contentgrid.registry.v1.Slot
	(*SlotLease)(nil),                       // 11: contentgrid.registry.v1.SlotLease
}
var file_contentgrid_registry_v1_types_proto_depIdxs = []int32{
	0, // 0: contentgrid.registry.v1.Website.status:type_name -> contentgrid.registry.v1.WebsiteStatus
	4, // 1: contentgrid.registry.v1.VerifierAssignment.assignment:type_name -> contentgrid.registry.v1.PublisherVerificationAssignment
	5, // 2: contentgrid.registry.v1.VerifierAssignment.submission:type_name -> contentgrid.registry.v1.PublisherVerificationSubmission
	1, // 3: contentgrid.registry.v1.Slot.status:type_name -> contentgrid.registry.v1.SlotStatus
	2, // 4: contentgrid.registry.v1.SlotLease.status:type_name -> contentgrid.registry.v1.LeaseStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_contentgrid_registry_v1_types_proto_init() }
func file_contentgrid_registry_v1_types_proto_init() {
	if File_contentgrid_registry_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentgrid_registry_v1_types_proto_rawDesc), len(file_contentgrid_registry_v1_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contentgrid_registry_v1_types_proto_goTypes,
		DependencyIndexes: file_contentgrid_registry_v1_types_proto_depIdxs,
		EnumInfos:         file_contentgrid_registry_v1_types_proto_enumTypes,
		MessageInfos:      file_contentgrid_registry_v1_types_proto_msgTypes,
	}.Build()
	File_contentgrid_registry_v1_types_proto = out.File
	file_contentgrid_registry_v1_types_proto_goTypes = nil
	file_contentgrid_registry_v1_types_proto_depIdxs = nil
}
